# Introduction

*Sebastes entomelas* (Widow Rockfish) is named after its black-lined gut cavity (*ento* meaning within and *melas* meaning black). It has been referred to as buda, beccafico (Italian bird), and viuva (widow) prior to the 1930s. More recently, the Widow Rockfish is also called brownie, belinda bass, brown bomber, and soft brown.

This is an assessment of Widow Rockfish that inhabit the waters off California, Oregon, and Washington from the U.S.-Canadian border in the north to the U.S.-Mexico border in the south, and does not include Puget Sound waters (Figure 1). This assessment represents a thorough reconsideration of the data, data preparation, and model structure for assessing Widow Rockfish, including reinvestigations of recent and historical catches (including discards), length and age data, and fleet structure.

## Distribution and Stock Structure

Widow Rockfish inhabit water depths of 25–370 m from northern Baja California, Mexico to Southeastern Alaska, and are most abundant from British Columbia to Northern California. Although catches north of the U.S.-Canada border or south of the U.S.-Mexico border were not included in this assessment, it is possible that these populations contribute to the biomass of Widow Rockfish off of the U.S. West Coast through adult migration and/or larval dispersion.

There is little evidence of genetically separate stocks along the U.S. coast and past assessments have used a single area, coastwide model with multiple fisheries [@he_status_2011]. In 2011, a two-area assessment model was brought forward for review, and was found to be similar to a coastwide model [@he_status_2011]. There is some evidence of biological differences between areas. For example, Widow Rockfish collected off California tend to mature at a smaller length than Widow Rockfish collected off of Oregon [@barss_maturity_1980]. This may be due to environmental or anthropogenic effects rather than genetic differences. The connectivity of Widow Rockfish populations throughout its range is unknown and it was decided to continue with a single area model for this assessment instead of potentially lose prediction power by splitting the data into two separate areas.

## Life History and Ecosystem Interactions

Widow Rockfish are atypical for West Coast rockfish species because they form dense midwater aggregations at night, which were largely undetected until the late 1970s. They are typically found over high relief strata and near cobblestone. The diet of Widow Rockfish is dominated by species that comprise the deep scattering layers, including salps, myctophids, *Sergestes similis* (a caridean shrimp), and euphausiids [@adams_diet_1987].

Widow Rockfish are ovoviviparous with gestation lasting from 1 to 3 months. Parturition occurs earlier in southern latitudes (December-March off California) than in northern latitudes (April in British Columbia) and occur once a year [@barss_maturity_1980]. Estimates of fecundity of Widow Rockfish range from 95,375 oocytes at 33 cm to 1,113,000 oocytes at 52 cm [@Boehlert_fecundity_1982].

There is little information regarding the movement of Widow Rockfish. Past assessments have assumed a two-area model because of differences in growth and maturity (see [@he_status_2011]). However, using recent observations from the NWFSC shelf/slope survey to follow two separate cohorts through time and space suggests that Widow Rockfish may recruit in the south and disperse northward as they age (Figure 2). Spatial recruitment and movement patterns of Widow Rockfish are uncertain and much more investigation and sampling is needed to fully understand them.

## Fishery description

Widow Rockfish were lightly exploited by bottom trawl and hook-and-line gears prior to the 1980s. After many attempts to start trawl fisheries off the west coast of the United States in the late 1800s, the availability of otter trawl nets and the diesel engine in the mid-1920s helped trawl fisheries expand [@douglas_species_1998]. The trawl fisheries really became established during World War II when demand increased for shark livers and bottomfish. A mink food fishery also developed during World War II [@jones_oregon_1960]. Foreign fleets began fishing for rockfish in the mid-1960s until the EEZ was implemented in 1977 [@rogers_species_2003]. Longline catches of Widow Rockfish are present from the turn of the century and continue in recent years, mainly from fisheries targeting sablefish and halibut.

In the late 1960s and early 1970s, it is reported that foreign fishing vessels caught large numbers of Widow Rockfish [@rogers_species_2003]. In the late 1970s a domestic midwater trawl fishery began developing off of Oregon when it was realized that Widow Rockfish form dense aggregations at night [@Gunderson_great_1984]. The fishery expanded very quickly, with landings from trawl, net, and hook-and-line gears increasing more than 20 times by the early 1980s (Table 1). As early as 1982, trip limits were imposed to keep catches below recommended annual levels (Table 3). Trip limits became more restrictive over the years until Widow Rockfish was declared overfished in 2001. In 2002, harvest guidelines were greatly reduced and over the last decade have been small, although increasing since 2004 (Table 4).

Historical discarding practices are not well known, but it is believed that little discarding occurred prior to management restrictions. With the introduction of trip limits, limited data from the mid-1980s show occasional very high discard rates of Widow Rockfish from tows that occurred near the end of a trip.

More detailed information of the fisheries in each state is given in Section 2.2.1 where the reconstructed landings are discussed.

## Management History and Performance

Widow Rockfish has been a small large component of groundfish fisheries since the late 1970s. The landings of Widow Rockfish have been historically governed by harvest guidelines and trip limits, while recently management is imposed with total catch harvest limits in the form of overfishing limits (OFLs), acceptable biological catches (ABCs), and annual catch limits (ACLs). A trawl rationalization program, consisting of an individual fishing quota (IFQ) or catch shares system was implemented in 2011 for the limited entry trawl fleet targeting non-whiting groundfish, including Widow Rockfish, and the trawl fleet targeting and delivering whiting to shore-based processors. The limited entry at-sea trawl sectors (motherships and catch-processors) that target whiting and process at sea are managed in a system of harvest cooperatives.

Limits on Widow Rockfish were first established in 1982 (Table 3). These were implemented as trip limits and cumulative landing limits that were first imposed by trip, then week, then every 2 weeks, month, 2 months, and eventually into periods. In many years, the trip limits on Widow Rockfish were significantly reduced at the end of the year to avoid exceeding the harvest recommendations. Some important years were 1985 when trip limits were reduced to 30,000 pounds once per week or 60,000 pounds once every 2 weeks, 1990 when trip limits were reduced to 15,000 or 25,000 pounds every one or two weeks, respectively, 1998 when a 25,000 pound cumulative limit per two-month period was implemented, and 2011 when catch shares was implemented.

A sorting requirement was implemented for Widow Rockfish in the early 1980s with California beginning in 1982, Oregon in 1984, and Washington in 1988. Some important events that could affect fishery selectivity are the gear restrictions implemented in 2000, implementation of Rockfish Conservation Areas (RCA’s) in 2002, seasonal changes to the RCA’s in 2007, and the beginning of catch shares in 2011.

Table 4 shows that recent landings have been below recommended catch levels. Landings are a considerable amount below the ACL, and it is unlikely that total mortality has exceeded the ACL in the last 10 years.

<!--
## Management performance

Management performance, including a table or tables comparing Overfishing Limit (OFL), Acceptable Biological Catch (ABC), Annual Catch Limit (ACL), landings, and catch (i.e., landings plus discard) for each area and year. Groundfish assessments that estimate dead discarded catch must include a disclaimer noting that total mortality estimates from the WCGOP and from the stock assessment may differ due to the use of different methods. Investigation into how these methods differ is beyond the scope of a benchmark assessment. The rationale for modeling discard mortality can also be provided. This should be included in all update assessments.
-->

## Fisheries off Canada and Alaska

Widow Rockfish are distributed throughout Canada and Southeast Alaska and are commonly caught in trawl and hook-and-line fisheries. However, the landings from the fisheries in these areas are estimated to harvest Widow Rockfish at much smaller rate than has been observed off California, Oregon, and Washington mostly due to lower abundance of Widow Rockfish, but also partly due to precautionary behavior of Canadian managers after the large catches followed by management restrictions and concerns of the U.S. fishery in the early 1980s.

Alaska formed the “Other Rockfish” complex in 2012 from the combination of Other Slope Rockfish and the Widow and Yellowtail Rockfishes from the Pelagic Shelf Rockfish category. This new complex includes 18 species and Widow Rockfish are a small proportion of the catch (less than 5%). Total biomass estimates are provided by the Gulf of Alaska (GOA) triennial/biennial trawl survey. ABC’s and OFL’s were set for the Other Rockfish Complex and component species in 2013 with a recommended OFL in 2014 of 5,347 mt for the complex. Widow Rockfish comprise a small part of this complex in Alaska.

The fishery for Widow Rockfish in British Columbia, Canada started in 1986 although some very small landings occurred in the mid-1970s. Landings peaked at about 4,500 mt in 1990 and were around 2,000 mt throughout the 1990s [dfo_widow_1999]. Most landings occurred in a midwater trawl fishery, but there have also been reports of “nuisance catches in the salmon troll fishery”. An assessment of Widow Rockfish in Canada was completed in 1998 [@stanley_shelf_1999] as part of a shelf rockfish complex. Additional research has since been done on the estimation of biomass of particular aggregations of Widow Rockfish [@stanley_estimation_2000], but no formal assessment has been done since.
