# Data

<!--- Provide temporal and spatial resolutions or sample size where appropriate for each of the subsections, below.--->
Many sources of data were available for this assessment, including indices of abundance (Table 5), landings, discards, and length and age observations from fishery-dependent and fishery-independent sources.

## Fishery-independent data

<!-- 
Fishery-independent data: Description of surveys used in the assessment, description of methods to estimate abundance indices, sample size information for length- and age- composition data by survey and year, including both the number of tows (or drops or sites for hook and line data) and fish sampled. Include complete tables and figures and date of data extraction. 

For pre-written descriptions of our main surveys, go here: https://github.com/pfmc-assessments/sa4ss/tree/main/inst/rmarkdown/templates/sa/skeleton
And copy the text from the files 21s-tri.Rmd and 21s-wcgbts.Rmd
-->

Data from three fishery-independent surveys were used in this assessment: 1) the SWFSC and NWFSC/PWCC Midwater Trawl Survey (hereafter, “juvenile survey”); 2) the Alaska Fisheries Science Center (AFSC)/NWFSC Triennial Shelf Trawl Survey (hereafter, “triennial survey”); and 3) the NWFSC West Coast Groundfish Bottom Trawl Survey (hereafter, “WCGBTS”). These surveys employed different designs and sampling methodologies, were conducted during different years and time periods within years, and included coverage over different areas of the coast. In some instances, the survey frequency, depths, and geographic areas covered were not internally consistent within surveys. A brief description of each survey is provided below. 

Strata were defined by latitude and depth to analyze the catch-rates, length compositions, and age compositions using stratified random sampling theory (@tbl-depth-surv & @tbl-strat-surv). The latitude and depth breaks were chosen based on the design of the survey as well as by looking at biological patterns in relation to latitude and depth. Indices of abundance for all of the surveys were derived using model based approaches described below.

### \acrlong{s-juv}

We updated the coastwide pre-recruit index of abundance for widow rockfish using data from three midwater trawl surveys targeting young-of-the-year (YOY) rockfish (\gls{s-juv}), provided by Tanya Rogers (SWFSC, pers. comm.). All surveys used identical gear, enabling the construction of a consistent coastwide index spanning from 36°N to the U.S./Canada border since 2004. For building the widow rockfish pre-recruit index, we used data from 2001 to 2024 without spatial subsetting (including CA, OR, and WA). Sampling in 2020 was limited due to the COVID-19 pandemic and excluded from all models. In 2010 and 2012, coverage was incomplete, so these years were used to construct the index but excluded from the final model to align with the 2019 assessment.Following the 2019 assessment, data from 2001–2003 were also excluded following the 2015 assessment due to limited spatial coverage (36°30′ to 38°20′ N latitude). However, a sensitivity analysis was conducted to examine the impact of including those early years (see section: Sensitivity Analysis).

The index was built using a spatial GLM with the sdmTMB package [@anderson_sdmtmb_2022], modeling 100-day standardized catch-per-tow as a function of year (fixed effect), Julian date (GAM smoother, k = 4), spatial random field, and spatiotemporal random effects. Models with Tweedie, delta-lognormal, and delta-gamma error structures were compared; DHARMa residuals and simulation-based diagnostics indicated the Tweedie model performed best. The index shows a strong increasing trend in juvenile abundance from 2017 to 2023, with a slight decline in 2024. Despite the dip, recent values remain high relative to the previous decade, and uncertainty estimates support the robustness of this trend.

### \acrlong{s-tri}

The \gls{s-tri} was first conducted by the \gls{afsc} in 1977, and was conducted every three years  until 2004 [@weinberg_estimation_2002]. Its basic design was a series of equally-spaced east-to-west transects across the continental shelf from which searches for tows in a specific depth range were initiated. The survey design changed slightly over time. In general, all of the surveys were conducted in the mid summer through early fall. The 1977 survey was conducted from early July through late September. The surveys from 1980 through 1989 were conducted from the middle of July to late September. The 1992 survey was conducted from the middle of July through early October. The 1995 survey was conducted from early June through late August. The 1998 survey was conducted from early June through early August. Finally, the 2001 and 2004 surveys were conducted from May to July (@fig-dist-opdates).

Haul depths ranged from 91--457 m during the 1977 survey. Due to haul performance issues and truncated sampling with respect to depth, the data from 1977 were omitted from this analysis. The surveys in 1980, 1983, and 1986 covered the U.S. West Coast south to 36.8\textdegree N latitude and a depth range of 55--366 m. The surveys in 1989 and 1992 covered the same depth range but extended the southern range to 34.5\textdegree N (near Point Conception). From 1995 through 2004, the surveys covered the depth range 55--500 m and surveyed south to 34.5\textdegree N. In 2004, the final year of the \gls{s-tri} series, \gls{nwfsc} \gls{fram} conducted the survey following similar protocols to earlier years. 

Following the 2015 assessment, the triennial index was estimated using a delta-generalized linear mixed model (GLMM) following the methods of [@thorson_accounting_2013]. The survey were stratified by latitude and depth, with the stratifications shown in @tbl-strat-surv. The Delta-GLMM approach explicitly models both the zero and non-zero catches and allows for skewness in the distribution of catch rates and vessel-specific differences in catchability (via inclusion of random effects). Multiple error structures were considered in 2015, including lognormal and gamma error structures with and without extreme catch events. The gamma distribution with random strata-year effects accounting for extreme catch events fit the data the best using median deviance values and Deviance Information Criterion (DIC) values and thus was used in 2015, 2019 and here, in the 2025 assessment (though see sensitivity run for model without the triennial survey index). The time series suggests a possible slightly increasing trend in biomass from 1980–1983, although is relatively flat until the end of the period in 2001 and 2004 when the index declines significantly. 

### \acrlong{s-wcgbt}

The \gls{s-wcgbt} is based on a random-grid design; covering the coastal waters between depths of 55--1,280 m [@bradburn_2003_2011]. This design generally uses four industry-chartered vessels per year assigned to a roughly equal number of randomly selected grid cells and divided into two `passes' of the coast. Two vessels fish from north to south during each pass between late May to early October. There were only two vessels used in 2019 and three in 2013, with one of the three that year unable to complete its survey pass due to a government shutdown. No survey occurred in 2020 due to \gls{covid}. This design therefore incorporates both vessel-to-vessel differences in catchability, as well as variance associated with selecting a relatively small number (approximately 700) of possible cells from a very large set of possible cells spread from the Mexican to the Canadian borders. Note that the Survey is not permitted to access the \glspl{cca} in Southern California.

Widow rockfish are not commonly caught in the WCGBTS. Higher catch rates occur north of 40° N latitude and catches are rare south of 36° N latitude (@fig-assess-map). Few large fish are found shallower than 100 m and few small fish are found in the deeper water of the slope. There is no clear trend in length with latitude other than smaller fish tend to occur south of approximately 36° N latitude, and there appears to be some very small fish found near 39° N latitude.

Geostatistical models of biomass density were fit to survey data using the R package \gls{sdmtmb} [@anderson_sdmtmb_2022]. This approach reflects an updated approach compared to the 2015 assessment (non-spatial delta-GLMM) and the 2019 update assessment (VAST delta-lognormal model). These models can account for latent spatial factors with a constant spatial Gaussian random field and spatiotemporal deviations to evolve as a random walk Guassian random field using a 200 knot grid of the survey area [@thorson_geostatistical_2015]. The prediction grid was also truncated to only include available survey locations in depths between 55--500 m to limit extrapolating beyond the data and edge effects. Tweedie, delta-binomial, delta-gamma, and mixture distributions, which allow for extreme catch events, were investigated. The positive catch weight model includes survey pass ('first' for early season or 'second' for late season) and year. Vessel-year effects, which have traditionally been included in index standardization for this survey, were not included as the estimated variance for the random effect was close to zero. Vessel-year effects were more prominent when models did not include spatial effects and were included for each unique combination of vessel and year in the data to account for the random selection of commercial vessels used during sampling [@helser_generalized_2004; @thorson_accounting_2014]. 

Results are only shown for the delta-gamma and delta-lognormal distributions, which reported the best diagnostics among the explored models. Both models converged (positive, definite Hessian matrix) but predicted data from both models showed slightly right-heavy tails compared to null expectations, with the gamma model having stronger divergence. The delta-lognormal distribution ultimately had the best model diagnostics, e.g., similar distributions of theoretical normal quantiles and model quantiles, high precision, lack of extreme predictions that are incompatible with the life history, and low \gls{aic}. Spatiotemporal estimates of positive catch for the delta-lognormal distribution were then converted into annual indices using sdmtmb::get_index() function informed by the spatial bounds of the survey [@anderson_sdmtmb_2022].

The index estimate is relatively stable, with a slightly increasing trend in recent years and a moderate peak in 2016. Overall, the delta-lognormal index estimates were more comparable to the 2019 spatiotemporal VAST-based index than the delta-gamma index, and seemed less influenced by potential extreme catch events, particularly in 2013 and 2016; for these reasons, in addition to better model performance described above, the delta-lognormal sdmTMB-based index was used for the base model in this assessment. The delta-lognormal mean value (2262.824) was slightly lower than the means of the index values used in the 2015 assessment (2701.12) and the 2019 update assessment (3301.765). Comparisons of the different error structures, design-based estimate and the VAST index used in 2019 are in @fig-absurv-compare. 

Length, age, and conditional age-at-length compositions were created by expanding to the tow and summing to give a strata specific composition (Table 9). The strata compositions were combined to a coastwide composition using a design-based index of abundance from each strata. The design based index is constructed by taking the average catch per unit effort (CPUE) defined as catch per area swept across tows in each stratum and year. The sum of strata specific composition data was then calculated, weighting by the average CPUE per stratum multiplied by the area of each stratum. The 2015 assessment weighted composition data by a Delta-GLMM. Unsexed fish were apportioned to males and females according to the estimated sex ratio for lengths greater than 28 cm. The sex ratio of lengths less than 28 cm was assumed to be 0.5. The design based weighting was selected because a Delta-GLMM based index was not constructed for this assessment and sdmTMB based weighting providing results inconsistent with the previous assessment. 

Expanded length frequencies from this survey show intermittent years of small fish; the 2018–2024 period generally suggests most fish are around 40–45cm in length (@fig-exp-lencomp-WCBTS). Age compositions (@fig-exp-agecomp-WCBTS) show a high proportion of a single age in 2004 and 2014, with a more even distribution of ages in the 2018–2024 period. Strong cohorts are not immediately apparent and it seems that ageing error may result in some variability between years. Conditional age-at-length proportions (@fig-cond-agelen-WCBTS) show relatively consistent length-at-age with few outliers.

## Fishery-dependent data

### Landings

Widow rockfish have been caught in trawl and hook-and-line fisheries since the early part of the 20th century. Widow rockfish are a desirable rockfish and are not likely to be discarded for market reasons. However, smaller widow rockfish are found at shallower depths and discarding practices in the early 1900s are uncertain. In data from the early 1980s, widow rockfish have had their own landing category, beginning in California in 1982, Oregon in 1984, and Washington in 1988. Estimates of historical landings of widow rockfish rely upon species-composition sampling data from each period. The uncertainty in species composition is greater in past years, with less systematic and extensive sampling occurring prior to 1980. Consequently, the precision with which landings of widow rockfish can be estimated likely decreases for earlier years.

The definitions of fishing fleets have not been changed from those in the 2015 and 2019 assessments. Five fishing fleets were specified within the model: 1) a shorebased bottom trawl fleet with coastwide catches from 1916–2024, 2) a shorebased midwater trawl fleet with coastwide catches from 1979–2024, 3) a mostly midwater trawl fleet that targets Pacific Hake/Whiting (Merluccius productus) and includes a foreign and at-sea fleet with catches from 1975–2024, a domestic shorebased fleet that targeted Pacific Hake with catches from 1991–2024, and foreign vessels that targeted Pacific Hake and rockfish between 1966–1976, 4) a net fishery consisting of catches mostly from California from 1981–2024, and 5) a hook-and-line fishery (predominantly longline) with coastwide catches from 1916–2024. As in previous assessments, catches from Puget Sound and those from commercial shrimp trawls, commercial pots, and recreational fisheries were excluded (as these are generally minimal).

Catches from all years (1916-2018) were carried forward into this assessment, with two exceptions. First, discards from the hook-and-line fleet were added to the removals for this fleet . The hook-and-line removals of widow rockfish are extremely minimal (@tbl-all_removals) and comprised only approximately 0.2% of the total removals over the last twenty years, with discard being a small fraction of that. The biological samples of the discard amount are also scarce, with input sample sizes not exceeding 6 and averaging around 3 per year (@tbl-disc-totals). With this limited data, the model was unable to reliably estimate retention parameters and exhibited substantial sensitivity to even slight changes in discard amounts within the hook-and-line fleet. Therefore, in this assessment, we added hook-and-line discards to hook-and-line landings. Second, because PacFIN appear to underestimate midwater trawl catches in California in 1979-1980 (Edward Dick, Pers. Comms.) we adjusted midwater and bottom trawl catches from California in these years to reflect the ratio of California midwater to bottom trawl catches in 1981-1982. New catches (2019-onward) from PacFIN and ASHOP were otherwise appended onto the 1916-2018 landings and apportioned among fleets using the same criteria as those documented in the 2015 assessment.

### Fishery catch-per-unit-effort

Three fishery-dependent CPUE indices were used as in the 2015 and 2019 assessments, derived from 1) Oregon bottom trawl (1984-1999), 2) Pacific Whiting at-sea foreign (1977-1988), and 3) Pacific whiting at-sea domestic fleets (1983-1998).

### Fishery length and age data

Biological data from commercial fisheries that caught Widow Rockfish were extracted from PacFIN (PSMFC) on March 25, 2025 and from the NORPAC database on XX X, XX. Lengths taken during port sampling in California, Oregon, and Washington were used to calculate length and age compositions. The data were classified into bottom trawl, midwater trawl, hake trawl, net, and hook-and-line fleets 

@tbl-num-land-length shows the number of landings sampled and @tbl-len-gear-state shows the number of lengths taken for each year, gear, and fleet from the three states. @tbl-landings-hake shows these numbers for the at-sea fleet. 

Consistent with the 2019 assessment, length and age samples from PacFIN were expanded up to the total landing then combined into state-specific frequencies (@tbl-sample-age-gear-state). Expansion factors were calculated in a way such that large expansions would not occur and based on ideas first presented by Owen Hamel (pers. comm., NWFSC). First the expansion factor (Ek) was the total catch weight (Wk) divided by the sample weight (wk), and raised to 0.9 to account for non-homogeneity within a trip. Then, expansion factors greater than 300 were capped (100 for net fisheries) to reduce the influence of small samples (i.e., a few fish representing a large catch). The predicted total numbers at length or age weighted by landings for each state were added to create a coast-wide length frequency. The effective sample sizes of the state combined length frequencies were determined from the following formula, which has been used in previous Widow Rockfish assessments as well as other west coast groundfish assessments.


| Fishery Samples                                  | Survey Samples                                   |
| :----------------------------------------------- | :------------------------------------------------ |
|  $\ N_{eff} = N_{sample} + 0.138N_{fish} , \frac{N_{fish}}{N_{sample}} < 44$ | $\ N_{eff} = N_{sample} + 0.0707N_{fish} , \frac{N_{fish}}{N_{sample}} < 55$ |
|  $\ N_{eff} = 7.06N_{sample} , \frac{N_{fish}}{N_{sample}} \geq 44$    | $\ N_{eff} = 4.89N_{sample} , \frac{N_{fish}}{N_{sample}} \geq 55$     |


This is slightly different from the sample size of 2.43 per haul for rockfish that Stewart & Hamel (2014) report. 

Observed lengths were expanded to the tow from At-Sea Hake Observer Program samples (ASHOP). Tows are typically well sampled, thus expansion factors were not modified from what was calculated. Hake fishery length compositions were created by combining shoreside and at-sea length compositions, weighting by the catch from each sector. The effective sample sizes for hake fishery length and age 9 comps were calculated using the above equations for the shoreside fleet and added to the number of tows sampled from the at-sea fleet. 

Expanded length compositions for bottom trawl, midwater trawl, hake fisheries, net, and hook-and-line are shown in @fig-lencomp-fleet1 to @fig-lencomp-fleet5. It is quickly apparent that all of these fisheries rarely land fish less than 26 cm. All of the non-hake fleets show a strong cohort coming though in the late 1970s and early 1980s, the late 1980’s., the late 1990’s, the early 2000’s, the early 2010’s and the late 2010’s Sample sizes typically dropped off between 2000 - 2010, however have been increasing since 2010 with increased fishing. The exception is in hake fishery where nearly every tow is sampled. 

Age compositions for the five fleets are shown in @fig-agecomp-fleet1 and @fig-agecomp-fleet5. Occasional cohorts appear to move through the population, indicating that Widow Rockfish population dynamics may be characterized by episodic recruitment events.


### Discards

Treatment and source of discard data was consistent with the 2019 assessment. Data on discards on Widow Rockfish are available from three different sources. The earliest source is called the Pikitch data and comes from a study organized by Ellen Pikitch that collected data on trawl discards from 1985–1987 (John Wallace, pers. comm and a manuscript in prep). The second source is called EDCP data, which stands for Enhanced groundfish Data Collection Project. These data were collected from late 1995 to early 1999 by at-sea observers on vessels that voluntarily participated in the project. These data were obtained from John Wallace (NWFSC, pers. comm.) and a report to the Oregon Trawl Commission written by David Sampson describes the data. The third data source is from the West Coast Groundfish Observer Program (WCGOP). This program is part of the NWFSC and has been recording discard observations since 2003. 

Results of the Pikitch data were obtained from John Wallace (NWFSC, pers. comm.) in the form of ratios of discard weight to retained weight of Widow Rockfish and sex-specific length frequencies. Although results were extended to additional years using data from a mesh study, it was decided to use only the results from the specific years of the study since there were many observations from those years (1985– 1987). Discard estimates are shown in @tbl-disc-totals and range from 463 to 1,847 mt. Length compositions for discards show a wide range of sizes being discarded, with a peak around 40 cm (@fig-disccomps-pikitch). 

Observations of discards from the EDCP dataset were provided as total discards and total landings per trip (i.e., fish ticket). For each year, the discards were summed and divided by the total observed landings to provide a ratio of discarded to retained catch. This was then applied to the total landings of that fleet to estimate total discards in that year (@fig-disccomps-pikitch). Variability was estimated from individual trip discard ratios. Length data were not available. 

The WCGOP has been collecting on-vessel data since 2002 to mainly record discard information, and are current through 2023. A proportion of the fleet for various gear types has been observed in each year and the data collected are used to estimate the total mortality for various species. Since 2011, under trawl rationalization, 100% observer coverage is required for the limited entry trawl sectors, which resulted in a large increase in data and ability to determine discard behavior. However, given the change in management, it is likely that there has been a change in discarding behavior. 


Widow Rockfish discard lengths composition data are available for the bottom trawl and midwater fleets. The bottom trawl data for 1985-87 is from the Pickitch study, and is unchanged from the 2019 assessment. Discard length data for 2004-2023 was provided by WCGOP. Historic WCGOP discard lengths from 2004 – 2017 are unchanged for the bottom trawl fleet, and new data are available for all consecutive years through 2023. Major changes occurred only in the treatment of the hook-and-line discard data. Historic discard lengths for the hook & line fleet provided by WCGOP this year were corrected to omit nearshore fixed gear fleets, which were included with the hook-and-line fleet in the previous benchmark and update assessments. This change resulted in changes to the discard length distribution and years for which data was available. The hook-and-line removals comprised only approximately 0.2% of the total removals over the last twenty years (@tbl-all_removals), with discard being a small fraction of that. The biological samples of the discard amount are also scarce, with input sample sizes not exceeding 6 and averaging around 3 per year. With this limited data, the model was unable to reliably estimate retention parameters and exhibited substantial sensitivity to even slight changes in discard amounts within the hook-and-line fleet. Therefore, in this assessment, we added the hook-and-line discard to hook-and-line landings. Discard length composition data, which are newly available from WCGOP for midwater fleets (hake, rockfish) beginning in 2016, were not included in this updated assessment as this would require major changes to the model structure which are beyond the scope of this update assessment but will need to be considered in the next full assessment.

Table 18 shows the number of vessels, trips, hauls with Widow Rockfish and the number of Widow Rockfish observed by the WCGOP in the years 2002–2013 for each fleet. One year of data from midwater trawl had to be removed due to confidentiality (at least three vessels need to be observed within a year, regardless of species caught, for the strata defined). Sample sizes are largest for bottom trawl and least for hook-and-line. Midwater trawl and shoreside hake were sampled in few years, mostly since 2011. Since 2011, when the trawl rationalization program was implemented, observer coverage rates increased to nearly 100% for all the limited entry trawl vessels in the program. Open access and non- sablefish fixed gear fisheries have continued with observer rates less than 13% of all groundfish landings 9 (WCGOP report,http://www.nwfsc.noaa.gov/research/divisions/fram/observation/data_products/sector_products.cfm). 

@fig-disccomps-pikitch shows discard totals in metric tons for each year, the source of the discard data, and whether it was included in the assessment. Coefficients of variation (CV) are set to 5% for years/fleets with 100% observer coverage. For the non-catch shares sectors the WCGOP errors were calculated by bootstrapping vessels within ports because the observer program randomly chooses vessels within ports to be observed. 

Total discards were estimated for varying numbers of years across fleets (@fig-disccomps-pikitch). Discards in the bottom trawl fleet were estimated for all available years (2002–2023), and discard rates (d/[d+r]) were typically greater than 50% prior to implementation of the trawl rationalization program in 2011, but less than 5% thereafter. The hook-and-line fleet discard rates ranged from 0% to 100% although quantities were low for all years (<0.2 mt). Observations of the midwater trawl fleet were available in only one year prior to catch-shares (2002), and every year post-catch shares (2011-2023). The discard ratio was 42.5% in 2002. The discarded amounts were virtually 0 in 2012 and 2013 and then have continuously increased in the 2014-2018 period (from 0.01 mt in 2014 to 37.2 mt  in 2018, @fig-disccomps-pikitch). The discard quantities remain at an average level of  33.8mt for the period 2018-2023. However, the discard rates remain low (<0.5%) for the entire period (2011-2023). The shoreside hake fleet was only observed post- trawl rationalization, and even though they do not typically sort the catch at-sea, 2011 showed a discard rate of 9.6%. This was mainly the result of a single very large discard event recorded in the observer database, and because it was not indicative of more recent years and the shoreside hake fishery is managed under a maximum retention regulation, discard estimates were simply added to landings and not modeled separately for this fleet. No observations of the net fleet were available even though a very small amount of Widow Rockfish was landed by this gear between 2002 and 2023. Overall, this period of time (2002–2023) is a period with highly regulated fisheries, and discarding could have been a result of trip limits being reached. Therefore, these numbers may not be indicative of previous years when the fishery was not as tightly regulated. Variability from bootstrapping the discard data often had a long tail or was characterized by small discards or large discards, indicating that tow-specific discard rates were sometimes zero and sometimes near 100%.

Length compositions of the discards for the bottom trawl are in @fig-disccomps-wcgop. These discards were used to fit the model. Estimated total catches, the sum of estimated discards and fixed landings, are reported.


 

$$
D_{y,f} = \frac{d_{y,f}}{r_{y,f}} R_{y,f}
$$


### Biological data

#### Weight-length relationship 
Weight-at-length data were updated from the 2019 assessment. Data used to estimate the length-weight relationship for widow rockfish (Figure 30 -TBC) were gathered from commercial catch sampling schemes (PACFIN,ASHOP), discard sampling schemes (WCGOP) and fishery-independent surveys (Triennial and NWFSC WCGBT Survey). Weight-at-length was similar between sources with the fishery samples showing a slightly smaller weight at large sizes when compared to the survey data (@fig-wl-fits). WCGOP data were not used because only small fish were sampled, the weight of these small fish were typically less than from other sources (Figure 30 - TBC), and the curves fitted to only WCGOP data were unable to estimate the slope. There were only 81 observations from the WCGOP data, which is a small amount of data compared to everything available. However, these observations may be useful to understand discards.

The weight-length relationship used in the 2011 assessment was similar for males but predicted slightly heavier females at larger sizes than the 2015 assessment (@fig-wl-fits). The following relationships between weight and length for females and males were estimated for the 2015 assessment from all of the data combined and were used in the current assessment:


$$
\text{Females: } \qquad weight = 1.7355 \times 10^{-5} \cdot Length^{2.9617}
$$

$$
\text{Males: } \qquad weight = 1.4824 \times 10^{-5} \cdot Length^{3.0047}
$$

where weight is measured in kilograms and length in cm. These relationships were used in the assessment as fixed relationships.


#### Maturity schedule
Estimates of maturity used in this update were the same as the 2019 assessment. Estimates of maturity at length have been presented by [@barss_maturity_1987], [@echeverria_thirty-four_1987], and [@love_life_1990]. [@barss_maturity_1987] supplied data collected from Oregon and California commercial and recreational samples, which allowed us to estimate the proportion mature-at-length and proportion mature-at-age for samples from each state (@fig-matlen-matage). As noted by [@barss_maturity_1987], the samples from Oregon matured at older age and larger length. Estimates of maturity-at-length from California reported by [@barss_maturity_1987] are similar to estimates of length-at-50%-mature from samples collected in California reported by [@echeverria_thirty-four_1987] and [@love_life_1990], although [@barss_maturity_1987] show the smallest length-at-50%-mature. To maintain some consistency with the 2011 assessment and to avoid any potential growth issues by area, the 2015 assessment used maturity-at-age data from the 2011 assessment, but used the data provided by [@barss_maturity_1987] to estimate a new maturity curve following a logistic function with the data from California and Oregon equally weighted to avoid California dominating the estimated relationship. This maturity-at-age curve falls between the estimated California and Oregon maturity-at-age curves (@fig-matlen-matage, right), with the age-at-50%-mature estimated at 5.47 and with a slope of -0.7747 (as specified in SS). This logistic maturity-at-age curve was used in the 2015 and 2019 update assessment except that maturity-at-age for ages 2 and lower were set equal to zero (Table 19 - TBC).

#### Fecundity

Fecundity in rockfish is often not a linear function of weight, but increases faster at larger weights [@dick_modeling_2009]. Therefore, this relationship is often accounted for in rockfish assessments by using spawning output (numbers of eggs) to determine current status. [@dick_modeling_2009] did not find a significant relationship between the number of eggs per gram of body weight and body weight for widow rockfish. Therefore, spawning output was assumed to be proportional to weight, which is the same as spawning biomass, and is reported here.

#### Natural Mortality

Natural mortality used in this update differed from the 2015 assessment in the treatment of the prior. Past assessments of widow rockfish assumed constant natural mortality of 0.125 yr^-1^ or 0.15 yr^-1^. The 2011 assessment estimated M with a prior developed by Owen Hamel (NWFSC, pers. comm.) using methods described in [@hamel_method_2014]. This prior was based on a maximum age of 44 and 40 for females and males, respectively, a mean temperature of 8 degrees Celsius (about 150m deep off of Oregon), and a gonadosomatic index of 9.99% and 1.86% for females and males, respectively [@love_life_1990]. The sex-specific lognormal priors for M have medians of 0.124 yr^-1^ and 0.129 yr^-1^ for females and males, respectively, and a coefficient of variation (CV) of 30.7% for each sex. In 2015, discussions with Owen Hamel (NWFSC) led to the development of a new prior based solely on maximum age to use when estimating M. Using all of the available age data, a maximum age of 54 was determined for both females and males, although it has been rare to observe widow rockfish older than about 45 years old (@fig-n-at-age). This resulted in a prior with a much smaller median (0.0810 or -2.513284 in log space) and a larger standard deviation in log space (0.523694). For the update assessment, an updated meta-analysis resulted in a prior with a slightly smaller median than the 2015 assessment (0.10 or -2.30 in log space) and a smaller standard deviation in log space (0.438). @fig-NatMort-priors shows that these prior distributions are wide and not highly informative.

#### Length-at-age

Estimates of length-at-age used in this update were the same as the 2015 assessment. Two different labs have aged the majority of processed otoliths for widow rockfish. The SWFSC has been aging widow rockfish otoliths for many years, including all of the fishery data prior to 2011 and otoliths collected from the NWFSC WCGBT survey in 2009 and 2010. The Cooperative Ageing Project (CAP) in Newport, Oregon aged 1,100 otoliths from the NWFSC WCGBT survey, 2,026 otoliths provided by ASHOP, and 3,467 otoliths collected by port samplers. All of the commercial fishery samples were collected in the years 2011–2014. In total, there are 105,814 paired age and length observations ranging from 1978 to 2014. @fig-len-age-vonBert shows the lengths and ages for all years and all data as well as predicted von Bertalanffy fits to the data. Females grow larger than males and sex specific growth parameters were estimated at the following values:




$$
\text{Females: } \qquad  L_\infty = 49.52,\quad k=0.18, \quad t_0 = -2.98
$$

$$
\text{Males: } \qquad  L_\infty = 43.64,\quad k=0.24, \quad t_0 = -2.69
$$

The data from each source (ASHOP, port sampling/BDS, Triennial survey, and NWFSC survey) are shown in Figure 36. All of these sources are quite similar, especially observations from ASHOP and the NWFSC survey.Variance in length- at-age was estimated separately in the model For small lengths, CV was estimated 0.12 and 0.094 for females and males, respectively. For larger lengths, CV was estimated 0.048 and 0.057 for females and males, respectively. A von Bertalanffy growth curve was fit using these parameters (Figure 36).


#### Sex ratios

Females tend to grow larger than males and it is expected that the proportion of females approaches one at large lengths and is less than 0.5 at intermediate lengths. Figure 38 shows that the proportion of females at length from survey data is approximately 50% until approximately 34 cm, when the proportion of females drops below 50%. At lengths larger than 46 cm, the proportion of females increases rapidly to one, suggesting that few males grow larger than 50 cm.

#### Ageing bias and imprecision

Uncertainty surrounding the ageing-error process for widow rockfish used in the 2019 assessment was incorporated by estimating ageing error by age. No changes were made from the 2019 assessment for the update. Age-composition data used in the model were from break-and-burn and surface reads and were aged by the Cooperative Ageing Project (CAP) in Newport, Oregon and the SWFSC in Santa Cruz, California. 12 Break-and-burn double reads of 1788 otoliths were performed by both the CAP and the SWFSC lab combined. Additionally, 100 otoliths were read both by surface and break-and-burn methods. An ageing error estimate was made based on these double reads using a computational tool specifically developed for estimating ageing error [@punt_quantifying_2008], and using release 1.0.0 of the R package nwfscAgeingError [@thorson_nwfscageingerror_2012] for input and output diagnostics, publicly available at: https://github.com/nwfsc- assess/nwfscAgeingError. The maximum aged fish read by the surface reading method was 10 years and the cross otolith reads between the surface and break-and-burn ageing methods showed limited variation. Therefore, a unique ageing error was not created for surface read otoliths. A non-linear standard error was estimated by age where there is more variability in the estimated age of older fish was estimated for each reading lab (@tbl-age-error and @fig-est-age-error).


## Environmental and Ecosystem Data

This assessment did not use any environmental or ecosystem data related to the stock.