
```{r  echo=FALSE, results='hide', message=FALSE, warning=FALSE}

library(renv)
library(r4ss)

# exe_dir<- "/Users/sulca/Documents/Github/widow-assessment-update/models/2025 base model"
# 
# 
# # r4ss::run(dir= exe_dir,exe="/Users/sulca/Documents/Github/widow-assessment-update/ss_osx",show_in_console = TRUE, skipfinished = FALSE)
# 
# 
# 
# df <- load(here::here("report", "tables","reference_"),stringsAsFactors = FALSE)
# colnames(df) <- c("Label", "Estimate", "Lower.Interval", "Upper.Interval")
# 
# reference_points <- setNames(
#   lapply(seq_len(nrow(df)), function(i) {
#     vals <- df[i, c("Estimate", "Lower.Interval", "Upper.Interval")]
#     vals <- format(round(as.numeric(vals)), big.mark = ",", scientific = FALSE)
#     setNames(as.list(vals), c("Estimate", "Lower.Interval", "Upper.Interval"))
#   }),
#   nm = gsub("\\\\%", "%", df$Label)
# )


```

# Assessment model

The assessment followed the same model structure as the 2015 base assessment ([@hicks_status_2015]) and 2019 update assessment ([@adams_status_2019]).

## History of modeling approaches

This section is not required for an update assessment; please refer to the most recent full assessment ([@adams_status_2019]) for additional information.

<!-- The history of model approaches for all years prior 2019 is detailed in @hicks_status_2015. In 2017, the NMFS implemented a quota share (QS) reallocation rule which re-established a target fishery for widow rockfish by allocating quotas among permit holders based on historical allocations, removing daily vessel limits, and allowing the trading of QS -->

<!-- ([@national_marine_fisheries_service_nmfs_national_oceanic_and_atmospheric_administration_noaa_commerce_magnuson-stevens_2017]). The most recent update assessment was conducted in 2019 ([@adams_status_2019]). The 2019 assessment included updated data (landings, survey indices, length / age composition, and discards), an updated prior on natural mortality (M), updated fixed steepness, and routine model bridging steps, but the model was otherwise unchanged from the 2015 assessment. The assessment estimated spawning stock biomass (SSB) in 2018 to be near the unfished SSB. -->

## Responses to SSC Groundfish Subcommittee requests

To be completed after review.

## Model Structure and Assumptions

### Model Changes from the Last Assessment

The specifications of the assessment are listed in @tbl-speci-base-assess and are unchanged from the previous assessment ([@adams_status_2019]), except by updating data, the prior on natural mortality, time blocks on selectivity and retention parameters, and other routine model bridging steps.

Data updated from the 2019 assessment included landings, survey indices, age / length composition data, and discard data. The only major change to the treatment of data and fleets was the addition of hook-and-line discards to hook-and-line landings, and the accompanying removal of the likelihood for hook-and-line discards. Removals from the hook-and-line fleet are generally minimal, approximately 0.2% of the total removals in the last two decades, of which discards are a small fraction. Owing to the very limited discard sample size for this fleet, the model was unable to reliably estimate discards and these data displayed substantial leverage on the model. Updates to the data had the largest impact on SSB among the various model bridging steps undertaken; in particular, the addition of (non-hook-and-line) discard data resulted in a small decrease in absolute SSB prior to 1980 and a large decrease in absolute SSB from the mid 2010s through the current year (@fig-bridge2019-data). Changes from other data sources were smaller. See “Data” and “Model Bridging” sections for detail.

The structural changes to the model were minimal, and were limited to the addition of an additional block on midwater trawl retention (from 2011–2016) and hake selectivity (from 2020 onward). In addition, the 2025 model estimates retention in the midwater trawl in late years (2017 onward), whereas retention was fixed at 0.99 in the previous assessment. These changes were undertaken to address poor fit to midwater trawl discards and hake fleet length compositions, assumed to be due to management changes in 2017 and shifts in the spatial distribution of the hake fleet, respectively. Neither change had a discernible influence on the estimated SSB. See “Model Bridging” section for detail.

Other model bridging steps undertaken include updating the prior on natural mortality, updating fixed length-weight regression parameters, updating recruitment bias adjustment parameters, and amending initial values after jittering analyses suggested the model had converged to a local (but highly similar) minimum. None of these changes had a discernible effect on the model estimates; see “Parameters” and “Model Bridging” sections for detail.


#### Model Bridging

Due to significant impact of updating data on estimated absolute stock biomass (SSB), bridging steps are detailed below.   

The exploration of models began by bridging from the 2019 update assessment to SS3 version 3.30.2, which produced no discernible difference. We then focused on data bridging. Updating the catch series did not have a substantial effect on the historical biomass, and estimated the stock biomass increasing from 2000 to 2020 before decreasing up to the current period. Updating the model discards had the most significant impact on the absolute stock biomass (SSB), with a small decrease in absolute SSB prior to 1980 and a large decrease in absolute SSB from the mid 2010s through the current year (@fig-bridge2019-data). Updating model indices had a similar effect, while updating the age and length composition data increased the absolute stock biomass in the current period. Updates to discards likewise had the largest effect on relative SSB (fraction of unfished biomass); changes in relative SSB owing to all other datasets were in general small.


None of the model bridging steps had a substantial effect on the estimates of stock biomass (@fig-bridge2019-data). The model bridging changes included (1) updating the prior for natural mortality (M) to follow that recommended by [@hamel_development_2022], (2) updating fixed parameters of the male and female length-weight curve by fitting to data from the NWFSC WCGBT, ASHOP, and the triennial survey outside the model, (3) re-fitting the bias adjustment ramp for recruitment deviates, (4) adding a block on retention in the midwater trawl fishery from 2011-2016 and allowing estimation of retention in the final years of the model, which was previously fixed at 0.99, (5) adding a block to hake fleet selectivity from 2020-2024 (5) re-fitting the model using the MLE as initial values following a jittering analysis which revealed the previous MLE was a local minima. These changes collectively resulted in a very small decrease in relative SSB post-1990, and pairwise correlations among all shared parameters in these models were high (>0.999). Bridging from the previous prior on M to the ([@hamel_development_2022]) prior is detailed in the “priors” section.

To estimate discards in the model, time blocks for changes in selectivity and retention in discard data were used. Except for the aforementioned addition of blocks to the midwater trawl and hake fleets, the same structure for time blocks was used as in the previous assessment ([@adams_status_2019]) The addition of midwater trawl and hake fleets block was necessitated by poor fits to midwater trawl discards and the length composition data from the hake fleet in from 2020 - 2024, respectively. The poor fit to hake fleet length composition data may be due to the high variability in the distribution of the hake / pacific whiting fleet between years, as the fleet moves to avoid bycatch ([@holland_bycatch_2019]). Poor fit to midwater trawl discards is thought to be due to (1) the previous decision to fix late-year retention to 0.99 which represented an overestimate of the (very low) discards in 2011-2016, and (2) the reallocation of quota shares and subsequent increase in midwater trawl discards in 2017. These choices are described in more detail in the “fits to data” section.


<!-- The 2015 assessment attempted to estimate discards in the model, wherein the authors investigated time blocks for changes in selectivity and retention to match the limited discard data as best as possible. Using major changes in management (mainly in trip limits, @tbl-manage-act) and observed changes in landings, a set of blocks was found for the bottom trawl, midwater trawl, and hook-and-line fleets. In the spirit of parsimony, they used as few blocks as possible, allowed blocks only for time periods with data, and added new blocks when they felt they were justified by changes in management and they improved the fit to the data. The same structure was followed for the update, except for the aforementioned addition of blocks to the midwater trawl and hake fleets. The addition of midwater trawl and hake fleets block was necessitated by poor fits to midwater trawl discards and the length composition data from the hake fleet in from 2020 - 2024, respectively. The poor fit to hake fleet length composition data may be due to the high variability in the distribution of the hake / pacific whiting fleet between years, as the fleet moves to avoid bycatch [@holland_bycatch_2019]. Poor fit to midwater trawl discards is thought to be due to (1) the previous decision to fix late-year retention to 0.99 which represented an overestimate of the (very low) discards in 2011-2016, and (2) the reallocation of quota shares and subsequent increase in midwater trawl discards in 2017. These choices are described in more detail in the “fits to data” section. -->



### Modeling Platform and Structure

For this update assessment, new versions of the previously used software were used. Stock Synthesis v3.30.13  was used to estimate the parameters in the 2019 model. R4SS, version 1.35.3, along with  R version 3.5.3 were used to investigate and plot the 2019 model fits. For the update, Stock Synthesis v3.30.2 and R4SS, version 1.51.0, along with R version 4.5.0 were used. A summary of the data sources used in the model (details discussed above) is shown in Figure 40. Stock Synthesis has many options when setting up a model and the assessment model for Widow Rockfish was set up in the following manner.

### Model Overview

The model is a two-sex, age-structured model starting in 1916 with an accumulated age group at 40 years. Sex-specific growth and natural mortality were estimated. The lengths in the population were tracked by 1 cm intervals and the length data were binned into 2 cm intervals. A curvilinear ageing imprecision relationship was estimated and used to model ageing error. Fecundity was assumed to be proportional to body weight, thus spawning biomass was used as the measure of spawning output.

#### Model Fleets and Areas

 The assessment uses a single-area model, consistent with previous assessments ([@adams_status_2019]).  Multiple fisheries encounter Widow Rockfish. The definitions of fishing fleets have not been changed from previous assessments ([@adams_status_2019]). 
 <!--

<!--Five fishing fleets were specified within the model: 1) a shorebased bottom trawl fleet with coastwide catches from 1916–2024, 2) a shorebased midwater trawl fleet with coastwide catches from 1979–2024, 3) a mostly midwater trawl fleet that targets Pacific Hake/Whiting (Merluccius productus) and includes a foreign and at-sea fleet with catches from 1975–2024, a domestic shorebased fleet that targeted Pacific Hake with catches from 1991–2024, and foreign vessels that targeted Pacific Hake and rockfish between 1966–1976, 4) a net fishery consisting of catches mostly from California from 1981–2024, and 5) a hook-and-line fishery (predominantly longline) with coastwide catches from 1916–2024. As in previous assessments, catches from Puget Sound and those from commercial shrimp trawls, commercial pots, and recreational fisheries were excluded (as these are generally minimal). -->

<!-- The Triennial Shelf Survey was kept as a single series, as in the 2015 and 2019 assessment. Assessment of other groundfish have split this survey into an early and a late series, based mostly on the shift to deeper depths and the timing of the survey (see section 2.1.2), by estimating different catchability parameters and selectivity parameters for each period. Age data were not available for the Triennial survey, but were available for the NWFSC WCGBT survey and were entered into the model as conditional age-at-length. Length-frequencies were calculated for the Triennial and the NWFSC WCGBT surveys within each stratum, and then combined across strata using the biomass in each stratum, and then combined across strata using the biomass in each stratum as the weighting factor. This reduced the influence of a few fish observed in a large area.  -->

### Model Parameters 

#### Estimated and Fixed Parameters

There were 214 estimated parameters in the base model. These included one parameter for recruitment (R0), 10 sex-specific parameters for growth, two sex-specific natural mortality parameters, four parameters for extra variability on the survey indices (survey indices were fixed at zero), four parameters for the catchability of the hake series and the Triennial Shelf survey (the catchabilities for other surveys were calculated analytically), 49 parameters for selectivity, retention, and time blocking of the fleets, eight parameters for survey selectivity, 125 recruitment deviations, and 12 forecast recruitment deviations.

Fixed parameters in the model were as follows. Consistent with ([@adams_status_2019]), steepness was fixed at 0.72 as was the mean of the current west coast rockfish steepness prior as described above. A sensitivity analysis and a likelihood profile were done for steepness. The standard deviation of recruitment deviates was fixed at 0.60. Maturity at age was fixed as described in ([@adams_status_2019]). Length-weight parameters were fixed at estimates using length-weight observations from the NWFSC WCGBT survey (@fig-wl-fits and @tbl-bio-params). 

<!-- Dome-shaped selectivity was explored for both the fishery and the surveys in the 2015 assessment. Older Widow Rockfish are often found in deeper waters and may move into areas that limit their availability to fishing gear, especially trawl gear. Little evidence was found in 2015 for domed shape selectivity in all but the midwater trawl fleet.  -->

The final base model assumed asymptotic selectivity (using the double-normal formulation in SS3) for each fishery, except for the midwater trawl fishery. The NWFSC and Triennial surveys both used spline curves. All selectivity curves were length based and the same shape as the 2019 update, with the exception of the NWFSC survey fleet. The NWFSC survey fleet selectivity was estimated to be slightly lower at lengths greater than 45 cm, compared to the selectivity estimated in 2019.

Time blocks were used for selectivity and retention parameters in the bottom trawl, midwater trawl, hake and hook-and-line fisheries as indicated in @tbl-speci-base-assess.

#### Priors

The prior on natural mortality (M) in the previous assessment was defined as a lognormal with mean on the log-scale of ln(5.4/Amax) and SD(ln(M)) = 0.4384343 following analysis of the data in ([@then_evaluating_2015]) by Owen Hamel and the authors. In the current assessment the prior on M has been updated to reflect guidance from ([@hamel_development_2022]); the log-mean therefore remains unchanged while the log-SD has been set to 0.31. Using a maximum age of 54 the point estimate and median of the prior on M is 0.10.

The prior for steepness (h) assumes a beta distribution with parameters based on an update of the Dorn rockfish prior (commonly used in past West Coast rockfish assessments) conducted by Jim Thorson (pers. comm, NWFSC, NOAA) which was reviewed and endorsed by the SSC in 2015. During the stock assessment review, it was decided that the steepness prior should be developed without the past Widow Rockfish data to avoid using the same data to inform both the model prior and likelihood. Without Widow Rockfish, the prior used for the 2015 assessment was a beta distribution with mean = 0.798 and SD = 0.132 (corresponding beta parameters $\alpha$ = 6.59 and $\beta$ = 1.667). The 2019 update assessments used the current West Coast rockfish steepness prior with mean = 0.72 and SD = 0.16 ($\alpha$ = 4.95, $\beta$ = 1.93) which was approved for use in all rockfish stock assessments for 2019. This update assessment uses the same prior. 

#### Recruitment deviations

The specification of when to estimate recruitment deviations is an assumption that likely affects model uncertainty. It was decided to estimate recruitment deviations from 1900–2024 to appropriately quantify uncertainty. The earliest length-composition data occur in 1976 and the earliest age data were in 1978. The most informed years for estimating recruitment deviations based on available composition data were from about the mid-1970s to about 2014. The period from 1900-1970 was fit using an early series with little or no bias adjustment, the main period of recruitment deviates was 1971–2020 with an upward and downward ramping of bias adjustment, and 2021 onward was fit using forecast recruitment deviates with little bias adjustment. ([@methot_adjusting_2011]) summarize the reasoning behind varying levels of bias adjustment based on the information available to estimate the deviates. The standard deviation of recruitment variability (sigma- R) was assumed to be 0.6 in the 2015 assessment, based on iteratively tuning to a value slightly less than the observed variability of recruitment deviations in the period 1975–2010 in 2015 (@fig-recfit-bias).

Survey indices and total discards were fitted assuming a lognormal likelihood.

####  Sample weights

<!-- Following the 2015 assessment, the base model was iteratively reweighted using the approach described in [@mcallister_bayesian_1997] such that the various data sources were mostly consistent with each other in terms of the relationship between input and effective sample sizes. Length and age-at-length compositions from the NWFSC WCGBT survey were fit along with length and marginal age compositions from the fishery fleets. Length data started with a sample size determined from the equation listed in Section 2.2.3. Conditional age-at-length data assumed that each age was a random sample within the length bin and started with a sample size equal to the number of fish in that length bin. One extra variability parameter that was added to the input variance was estimated for each survey index series. Vessels present in the WCGOP data were bootstrapped to provide uncertainty of the total discard. -->

<!-- An alternative method to determine weightings for the different data sources is called the Francis method, which was based on equation TA1.8 in [@francis_data_2011]. This formulation looks at the mean length or age and the variance of the mean to determine if across years, the variability is explained by the model. If the variability around the mean does not encompass the model predictions, then that data source should be down-weighted. This method does account for correlation in the data (i.e., the multinomial distribution) as opposed to the [@mcallister_bayesian_1997] method of looking at the difference between individual observations and predictions. -->

As previous full assessment used the McAllister & Ianelli method ([@hicks_status_2015]) and changing the weighting method is outside the TORs for an update, Francis weighting method is presented as a sensitivity.

The 2019 update assessment weighted composition data via the lambdas ([@adams_status_2019]). In the current assessment, the method to weight the composition datasets in SS3 was to use variance adjustment factors as the weighting factors.  The fleet and data-type (length or age) factor was entered as variance adjustments factors until the harmonic mean of the effective sample sizes matched the mean of the adjusted input sample sizes ([@mcallister_bayesian_1997]). Once the weighting was determined, lambda factors for all fleets with both marginal length and marginal age compositions were down-weighted by 0.5 to account for the potential double use of data since length and age are observed from the same fish. 

### Key Assumptions and Structural Choices

This section is not required for an update assessment; please refer to the most recent full assessment ([@adams_status_2019]) for additional information.

<!-- The key assumptions in the model were that the assessed population is a single stock with biological parameters characterizing the entire coast, maturity at age has remained constant over the period modeled, weight-at-length has remained constant over the period modeled, the standard deviation in recruitment deviation is 0.60, and steepness is 0.72. These are simplifying assumptions that unfortunately cannot be verified or disproven. Sensitivity analyses were conducted for most of these assumptions to determine their effect on the results. Structurally, the model assumed that the catches from each fleet were representative of the coastwide population, instead of specific areas, and fishing mortality prior to 1916 was negligible. It also assumed that discards were low prior to 1982 and after 2010, though have been increasing after 2018.  -->


