
```{r  echo=FALSE, results='hide', message=FALSE, warning=FALSE}

# library(renv)

# 
#exe_dir<- "/Users/sulca/Documents/Github/widow-assessment-update/models/2025 base model"


#r4ss::run(dir= exe_dir,exe="ss_osx",show_in_console = TRUE, skipfinished = FALSE)


library(r4ss)

report <- SS_output(here::here("models","2025 base model"))

est_params <- report$estimated_non_dev_parameters

est_params["NatM_uniform_Fem_GP_1","Value"]

```


## Base Model Results

The base model parameter estimates along with approximate asymptotic standard errors are shown in Table 23 and the likelihood components are shown in Table 25. Estimates of key derived parameters and approximate 95% asymptotic confidence intervals are shown in Table 26. 

### Parameter Estimates

The estimates of natural mortality `r est_params["NatM_uniform_Fem_GP_1","Value"]` yr-1  and `r est_params["NatM_uniform_Mal_GP_1 ","Value"]` yr-1 for females and males, respectively) were higher than suggested by the medians of the prior distributions used in this assessment and the 2015 assessment. Fixing M at lower values than those estimates resulted in a pattern of reduced recruitment immediately before the fishery started. This suggests that the model is doing what it can to reduce the number of observations of older fish in the data. The estimates of M fall within the 95% confidence interval of the prior distribution (0.0425–0.237), and are shown in Figure 44. 

Estimating M is difficult in stock assessments, and the estimated values may represent model misspecification instead of the actual life-history trait. However, in alternative models to the base case model, the estimates of M were rarely less than 0.14 yr-1 (Table 29). Uncertainty in the estimated M was also much less than the range of the prior (Figure 44). The assumption that appeared to have the largest effect on M was introducing dome-shaped selectivity in the midwater trawl fleet, which made M smaller (Table 29). 

Selectivity curves were estimated for commercial and survey fleets and parameter estimates are provided in Table 24. The final base model assumed asymptotic selectivity (double-normal selectivity curve ) for each fishery, except for the midwater trawl fishery. The NWFSC and Triennial surveys both used spline curves. All selectivity curves were length-based and are the same shape as in the 2015 benchmark. Time blocks were used for the bottom trawl, midwater trawl and hook-and-line fisheries as indicated in Table 21. The estimated selectivity, retention, and keep (the product of selectivity and retention) curves for the trawl and hook-and-line fleets are shown in Figure 45. The selectivity curves showed a shift to larger fish in 2002 for the bottom trawl fishery and a shift to smaller fish in 2003 for the hook-and-line fishery. The bottom trawl shift is consistent with the introduction of the RCA and gear restrictions (shoreward of the 18 RCA) that virtually eliminated fishing in shelf habitats where smaller Widow Rockfish would more likely be encountered. Around this same time, the fixed-gear RCA specifications began preventing fishing between 30 and 100 fm. 

The retention curves showed a shift to retaining a lower percentage of fish since trip limits were introduced, but increases in recent years. The asymptote of the retention curve for the bottom trawl fishery sequentially decreased as more management restrictions were introduced to about 50% retention of larger fish in the 1998-2010 period. 

Midwater trawl and hook-and-line fisheries estimated an asymptote to retention just above 80% for the period 1983-2010. Both the selectivity for the hake fleet and the selectivity of the net fleet did not support dome-shaped selectivity (Figure 46). The estimated selectivity curves for the Triennial and NWFSC WCGBT surveys were similar to each other except that the triennial survey selected larger fish (Figure 46). The NWFSC WCGBT survey was no longer minimally dome-shaped as in the 2015 assessment. 

In 2015, additional survey variability (process error added directly to each year’s input variability) for the triennial and NWFSC WCGBT surveys was not estimated in the model because the estimate was zero. To avoid bound issues in estimation of the Hessian, the authors fixed these at zero because the model- based results provided reasonable estimates of variance. We retained the same modelling approach for the update assessment. The additional standard deviation added to the fishery-dependent indices was quite large, ranging from 0.16 for the bottom trawl index and 0.58 for the foreign at-sea hake fleet. The additional variability on the juvenile survey was the highest, at 0.83, giving the index very little weight in the model. 

The estimates of maximum size for both females and males (Table 23) were not unexpected given the data in Figure 35. Estimates of k were slightly different in the model, but that is expected when accounting for selectivity. Estimated growth curves are shown in (Figure 47). 

Estimates of recruitment suggest that the Widow Rockfish population is characterized by variable recruitment with occasional strong recruitments and periods of low recruitment (Figure 48). There is little information regarding recruitment prior to 1965, and the uncertainty in these estimates is expressed in the model. There are very large, but uncertain, estimates of recruitment in 2013, 1970, 2008, and 1971. Other large recruitment events (in descending order of magnitude) occurred in 1978, 2014, 1981, 2010, and 1991. The five lowest recruitments (in ascending order) occurred in 2012, 2011, 1976, 2007, and 1973. Estimates of recruitment appear to be episodic and characterized by periods of low recruitment. Two of the four largest estimated recruitments occurred in the last 11 years. 


### Fits to the Data

There are numerous types of data for which the fits are discussed: survey abundance indices, discard data (biomass and length compositions), length composition data for the fisheries and surveys, marginal age compositions for the fisheries, and conditional age-at-length observations for the NWFSC WCGBT survey. 

The fits to the four survey series are shown in Figure 51. The Triennial Shelf Survey was kept as a single series, as in the 2015 and 2019 assessments. Extra standard error was estimated for all of the series except for the two survey series (Table 23). None of the series showed patterns in residuals, and with the large amount of error, none of the series showed serious lack of fit. The recent NWFSC WCGBT survey showed a general increase from 2003 - 2015 followed by a general decrease from 2016 - 2024, which was also estimated in the base model (Figure 51, lower left). Low (2015, 2021, 2022) and high (2016) estimates of abundance did not fit well in the model.

Fitting the total observed discard amounts required time blocks (Figure 52). Fits to the trawl discards from the Pikitch data in 1985–1987 in the time block 1982–1989 were quite good. The EDCP data (1995–1999) were not fit as well. In the time block 1990–1997, the EDCP discard observations showed a high error, and the fits were within the confidence limits, but below the point estimate in two of the three years. The 2015 assessment introduced a time block in 1998 because a serious reduction in trip limits occurred in that year (Table 3) and continued to 2010. The EDCP data showed a very small amount of discarding, which was consistent with the WCGOP data from that time period, but in 1998 and 1999, landings from the bottom trawl fleet were very large compared to 2000–2010. Therefore, a large amount of discards were predicted for 1998 and 1999, which do not match the observations. It is believed that the EDCP observations in 1998 and 1999 are not indicative of the actual discards because the sample sizes from the EDCP data were small in those years, and 1999 had a few samples from early in the year and at the beginning of the two-month trip limit period. The predicted discards for the years 2002–2010 were small (ranging from 1.97 to 15.8 mt). Observed discards from WCGOP were low (mean 0.5 mt, SD 0.7 mt) following the implementation of catch shares in 2011. Following the reallocation of quota shares and re-establishment of a target fishery for widow rockfish in 2017, however, observed discards increased markedly (mean 30.4 mt), though with high interannual variability (SD 14.9 mt). 

The 2019 model applied four time blocks to retention, with constant fixed discard rates of 1% in both early years (1916-1981) and late years (2011 onward). With the addition of new discard data since the 2017 reallocation, however, the use of a fixed discard rate from 2011 onward resulted in poor fits to the discard data. Therefore the current assessment utilizes an additional block on retention from 2011-2016, with the final block beginning in 2017; retention is estimated in both the 2011-2016 and 2017-2024 time blocks, though it remains fixed for the earliest time block (1916-1981) at the value used in the previous assessment. The first time block with discard data was 1983 to 2001. Predicted discards for all three years of the Pikitch data (1985–1987) were underfit, but within the confidence limits (Figure 52). The fits to the EDCP data in 1997 and 1998 were underfit. The second time block was 2002 to 2010, which contained only one observation in 2002 (and was fit exactly, as expected). Discard rates were overestimated in 2012-2013 and underestimated in 2015-2016, though they were generally well fit in in the 2017-2024 time blocks.

Hook-and-line discard biological data was recently revised by WCGOP. Samples from
nearshore pot and net gears that were for previous assessments added to hook-and-line samples are now removed, according to current best practices. This update to the data resulted in two issues: i) reduced sample sizes and ii) length compositions which differed significantly from the 2019 assessment. As a result, retention parameters for the hook-and-line fleet were poorly informed, and the decision was made to combine hook-and-line discard and retained catch. Biological samples for hook-and-line discards were then removed from the model, and discards were not estimated for the hook-and-line fleet.

Fits to the length-composition data are displayed in two different ways: the Pearson residuals-at-length are shown for each year for all types of length compositions, and also compared across fleets. More detailed plots of fitted lines drawn over the plotted proportions at length are shown in Appendix A. Pearson residuals for the fisheries (Figure 53 to Figure 54) do not show consistent patterns, but they do show that some fleets are not fitting some cohorts. Each fleet also shows that there are periods where older fish are underfit, and periods when older fish are overfit. With a peaked length frequency distribution, it is common for these patterns to appear given shifts in the expected distribution due to sampling error, and time-varying parameters that are assumed time-invariant. The net fishery observed some very large fish in the first two years of data, but did not observe those fish in later years. This pattern was not seen in any other fishery. There were also years where females showed positive residuals (filled circle, observed > expected) and males showed negative residuals (e.g., Figure 53, early years of bottom trawl and midwater trawl). It is uncertain if this pattern is related to growth, sexing error, or to sex-specific selectivity (e.g., when Widow Rockfish aggregate, sexes possibly may be aggregating separately). Overall, the fits to commercial fishery length compositions showed some patterns that the 2015 assessment deemed to require complicated modelling assumptions to alleviate. However, the residuals were mostly less than 2 in absolute value, especially for fleets that were well informed by data. 

Looking at the fits to length compositions aggregated for all years shows that the general shape of the length distributions are captured (Figure 55). 

The fits to bottom trawl discard length frequencies were generally good except in the years since catch shares began. These recent years observed small fish, which the estimated selectivity of the trawl fleet did not allow for. There were no other years that showed small fish being caught by the trawl fleet. Attempting to explain these small fish with additional time blocks on selectivity and retention did not help because explaining the small fish in the discards worsened20 the fits to the landed and larger fish. Discards are extremely small in this time period, so it is unlikely that a misfit here will have a lot of effect on the model. Combining the discard length frequencies over years may not be appropriate for the bottom trawl fishery due to the likely changes in discarding practices, but Figure 56 shows the prediction of discarding smaller females than observed and a more peaked observed distribution of discarded males than predicted. 

The Triennial Shelf and NWFSC WCGBT surveys length frequencies showed underfitting of older fish in some years and underfitting of younger fish in others (Figure 57). The combined length frequencies across years were bimodal with a valley around 37 cm, and the model showed an indication of a bimodal distribution but was unable to adequately capture both peaks (Figure 55). The nonparametric selectivity pattern helped to reduce this pattern, but selectivity may be even more complicated for the surveys. 

Age data were fitted as marginal age compositions for the fishing fleets and as conditional age-at-length for the NWFSC WCGBT survey, which were expanded by tow and then by strata. Raw observations of age-at-length, which assumes that within each length bin the observed ages are a random sample of fish, were not used because they are inconsistent with the length compositions which are expanded. Using expanded age-at-length ensures that as the length bin size is increased, it approaches the expanded marginal age composition. Pearson residuals for the commercial fleets are shown in Figure 53 and Figure 54. For the trawl fisheries in Figure 53, there are diagonal patterns that mostly correspond to cohorts ageing through the years. However, there are instances where the diagonal seems to shift, such as the filled circles of the midwater trawl fishery on the lower left of the plot (years 1981–1991). The patterns match the length compositions residuals in some cases. The bottom trawl fishery shows the largest residuals in the most recent years, which could indicate a change in selectivity. The net and hook-and- line fits to age compositions (Figure 54) showed larger residuals than the trawl fisheries. As with the fits to the length compositions, the net fishery showed the inability to match the large number of older fish observed in the early years. There appears to be a strong shift in residuals in 1988 when a lack of fit to potentially a cohort appears. The residuals were typically less than 2 for fits to the age data. However, the female age compositions occasionally produced some large residuals that were not consistently seen in the male age compositions. Aggregating across years shows that the fit to age comps was good for the trawl fleets and less so for the net and hook-and-line fleets, which had smaller sample sizes (Figure 58). The aggregated data also showed that the predictions were often unable to fit the peak in the data.

The observed and expected age-at-length are shown in Figure 59 for the twelve years of the NWFSC WCGBT survey observations. The fits generally match the observations with some misfit at larger lengths. The standard deviation of age-at-length was variable and often the expectation was higher than the observations at larger lengths. Plots with the residuals for individual observations showed reasonably good fits to the conditional age-at-length data from the NWFSC shelf/combo survey (Figure 60). Some outliers are apparent, with large residuals mostly at smaller lengths for a given age.

### Population Trajectory

The estimates of natural mortality (0.1246 yr-1 and 0.1367 yr-1 for females and males, respectively) were lower than the 2019 update. The estimates of M fall within the 95% confidence interval of the prior distribution (0.0425–0.237), and are shown in Figure 44. 

Estimating M is difficult in stock assessments, and the estimated values may represent model misspecification instead of the actual life-history trait. However, in alternative models to the base case model, the estimates of M were rarely less than 0.12 yr-1 (Table 29). Uncertainty in the estimated M was also much less than the range of the prior (Figure 44). The assumption that appeared to have the largest effect on M was introducing dome-shaped selectivity in the midwater trawl fleet, which increased the estimate of M (Table 29). 

Selectivity curves were estimated for commercial and survey fleets and parameter estimates are provided in Table 24. The final base model assumed asymptotic selectivity (double-normal selectivity curve ) for each fishery, except for the midwater trawl fishery. The NWFSC and Triennial surveys both used spline curves.All selectivity curves were length based and the same shape as the 2019 update, with the exception of the NWFSC survey fleet.The NWFSC survey fleet selectivity was estimated to be slightly lower at lengths greater than 45 cm, compared to the selectivity estimated in 2019. Time blocks were used for the bottom trawl, midwater trawl, hake and hook-and-line fisheries as indicated in Table 21. Time blocks were used for the bottom trawl, midwater trawl, hake and hook-and-line fisheries as indicated in Table 21. The estimated selectivity, retention, and keep (the product of selectivity and retention) curves for the trawl and fleets are shown in Figure 45. 

The selectivity curves showed a shift to larger fish in 2002 for the bottom trawl fishery and a shift to smaller fish in 2003 for the hook-and-line fishery. The bottom trawl shift is consistent with the introduction of the RCA and gear restrictions (shoreward of the 18 RCA) that virtually eliminated fishing in shelf habitats where smaller Widow Rockfish would more likely be encountered. Around this same time, the fixed-gear RCA specifications began preventing fishing between 30 and 100 fm. 

The retention curves showed a shift to retaining a lower percentage of fish since trip limits were introduced, but increases in recent years. The asymptote of the retention curve for the bottom trawl fishery sequentially decreased as more management restrictions were introduced to about 50% retention of larger fish in the 1998-2010 period. 

The Midwater trawl fishery estimated an asymptote to retention just above 80% for the period 1983-2010. Both the selectivity for the hake fleet and the selectivity of the net fleet did not support dome-shaped selectivity (Figure 46). The estimated selectivity curves for the Triennial and NWFSC WCGBT surveys were similar to each other except that the triennial survey selected larger fish (Figure 46). The NWFSC WCGBT survey was minimally dome-shaped, and was similar to the selectivity observed for the NWFSC WCGBT survey in the 2015 base case assessment, however it differed from the asymptotic shape observed in the 2019 assessment.

In 2015, additional survey variability (process error added directly to each year’s input variability) for the triennial and NWFSC WCGBT surveys was not estimated in the model because the estimate was zero. To avoid bound issues in estimation of the Hessian, the authors fixed these at zero because the model- based results provided reasonable estimates of variance. We retained the same modelling approach for the update assessment. The additional standard deviation added to the fishery-dependent indices was quite large, ranging from 0.16 for the bottom trawl index and 0.58 for the foreign at-sea hake fleet. The additional variability on the juvenile survey was the highest, at 1.69, giving the index very little weight in the model. 

The estimates of maximum size for both females and males (Table 23) were not unexpected given the data in Figure 35. Estimates of k were slightly different in the model, but that is expected when accounting for selectivity. Estimated growth curves are shown in (Figure 47). 

Estimates of recruitment suggest that the Widow Rockfish population is characterized by variable recruitment with occasional strong recruitments and periods of low recruitment (Figure 48). There is little information regarding recruitment prior to 1965, and the uncertainty in these estimates is expressed in the model. There are very large, but uncertain, estimates of recruitment in 1970, 2008, 2016, and 1971. Other large recruitment events (in descending order of magnitude) occurred in 1978, 1981, 2010, 1991, and 1997. The five lowest recruitments (in ascending order) occurred in 2012, 2019, 2020, 2011, and 1976. Estimates of recruitment appear to be episodic and characterized by periods of low recruitment. 


