
```{r  echo=FALSE, results='hide', message=FALSE, warning=FALSE}
sens_table <- read.csv(here::here("figures", "sensitivities", "sens_table.csv"))
sens_base_ssb <- round(as.numeric(sens_table[28, 2:13])/as.numeric(sens_table[28, 2])*100, 2)
mod_names <- c("base model", 
               "fixing natural mortality to 0.1 (2015 assessment prior)", 
               "fixing natural mortality at 0.124 yr-1 for females and 0.129 yr-1 for males (2011 assessment prior)", 
               "forcing asymptotic selectivity on the midwater trawl fleet", 
               "fitting logistic curves for NWFSC WCGBT survey selectivity", 
               "including previously excluded shrimp trawls",
               "updated Washington catch reconstruction",
               "fixing steepness at 0.4", 
               "fixing steepness at 0.6", 
               "fixing steepness at 0.798 (2015 assessment value)", 
               "exclusion of the triennial survey",
               "weighting the composition data using the Francis method")

# to get capitalized mod_name
firstup <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}
```

## Model Diagnostics

<!-- If a range of model runs is used to characterize uncertainty, it is important to provide some qualitative or quantitative information about relative probability of each. If no statements about relative probability can be made, then it is important to state that all scenarios (or all scenarios between the bounds depicted by the runs) are equally likely.  
If possible, ranges depicting uncertainty should include at least three runs: (a) one judged most probable; (b) at least one that depicts the range of uncertainty in the direction of lower current biomass levels; and (c) one that depicts the range of uncertainty in the direction of higher current biomass levels. The entire range of uncertainty should be carried through stock projections and decision table analyses.  -->

Three types of uncertainty are presented for the assessment of Widow Rockfish. First, uncertainty in the parameter estimates was determined using approximate asymptotic estimates of the standard error. These estimates were based on the maximum likelihood theory that the inverse of the Hessian matrix (the second derivative of the log-likelihood function with respect to the parameter vector) approaches the true uncertainty of the parameter estimates as the sample size approaches infinity. This approach takes into account the uncertainty in the data and supplies correlation estimates between parameters, but does not capture possible skewness in the error distribution of the parameters and may not accurately estimate the standard error in some cases (see [@stewart_comparison_2013]).

The second type of uncertainty that is presented is related to modeling and structural error. This uncertainty cannot be captured in the base model as it is related to errors in the assumptions used in specifying the base model. Therefore, sensitivity analyses were conducted where assumptions were modified to reveal the effect they have on the model results.

Lastly, a major axis of uncertainty was determined from a parameter or structural assumption that results in the greatest change in stock status and advice, and projections were made for different states of nature based upon that parameter or structural assumption.

### Convergence

<!-- Convergence status and convergence criteria for the base-run model (or proposed base run). Randomization of starting parameter value run (e.g., jitter) results or other evidence of search for global best estimates.  -->

### Parameter Uncertainty

Parameter estimates are shown in Table 22, Table 23, and Table 28 along with approximate asymptotic standard errors. The only parameters with an absolute value of correlation greater than 0.95 were the female and male natural mortality parameters, which is expected. Estimates of key derived quantities are given in Table 26 along with approximate 95% asymptotic confidence intervals. There is a reasonable amount of uncertainty in the estimates of biomass. The confidence interval of the 2019 estimate of depletion is XX%–XX% and above the management target of 40% of the unfished spawning biomass.

### Sensitivity Analyses

<!-- Sensitivity to assumptions about model structure, i.e., model specification uncertainty.  -->

<!-- Sensitivity to data set choice (e.g., using emphasis factors to selectively remove data sources) and weighting schemes (e.g., [@mcallister_bayesian_1997] weighting versus Francis weighting vs. Dirichlet weighting for compositional data), which may also include a consideration of recent patterns in recruitment.  -->

Sensitivity analysis was performed to determine the model behavior under different assumptions than those of the base case model. `r length(mod_names)-1` sensitivity analyses were conducted to explore the potential differences in model structure and assumptions, including:

1. Fixed natural mortality at 0.1 for both sexes (2015 assessment prior)
2. Fixed natural mortality at 0.124 yr-1 for females and 0.129 yr-1 for males (2011 assessment prior)
3. Fixed steepness at 0.4
4. Fixed steepness at 0.6
5. Fixed steepness at 0.798 (2015 assessment value)
6. Forcing asymptotic selectivity on the midwater trawl fleet
7. Fitting logistic curves for NWFSC WCGBT survey selectivities
8. Weighting the composition data using the Francis method
9. Updated Washington catch reconstruction
10. Inclusion of previously excluded shrimp trawl data
11. Exclusion of triennial survey data

Likelihood values and estimates of key parameters are shown in Table 29. Predicted spawning biomass trajectories, estimated recruitment deviations and comparisions of model estimates for 2025 are shown in in Figure 65 (sens_compare2_spawningbio_uncertainty.png), Figure XX (sens_compare11_recdevs.png) and Figure XX (sens_summary.png). The estimates of current stock depletion ranged from `r min(sens_base_ssb)`%-`r max(sens_base_ssb)`% across the sensitivity runs, with `r mod_names[which(sens_base_ssb == min(sens_base_ssb))]` resulting in the lowest estimate and `r mod_names[which(sens_base_ssb == max(sens_base_ssb))]` resulting in the highest estimate. Generally, the trajectory of the spawning biomass was qualitatively similar across all tested models, e.g., peak around late 1970s and late 2010s, projected decrease in biomass in 2025 followed by some recovery into the 2030s; the quantitative magnitude of these trends did vary across cases. 

Fixing M at values lower than the base case estimate resulted in decreases in estimated spawning biomass, while fixing steepness across the values tested resulted in similar or increased estimated spawning biomass. The relative spawning biomass in 2025 changed to `r sens_base_ssb[which(mod_names=="fixing natural mortality at 0.124 yr-1 for females and 0.129 yr-1 for males (2011 assessment prior)")]`% with an M of 0.124 yr-1 and 0.129 yr-1 for females and males, respectively (2011 assessment prior), and to `r sens_base_ssb[which(mod_names=="fixing natural mortality to 0.1 (2015 assessment prior)")]`% with an M of 0.1 yr-1 (2015 assessment prior). 

Fixing steepness at a value of 0.6 resulted in an increase of the spawning biomass to `r sens_base_ssb[which(mod_names=="fixing steepness at 0.6")]`% and a decrease in equilibrium yield at a SPR50% reference harvest rate, while other tested values for fixed steepness increased spawning biomass slightly (`r sens_base_ssb[which(mod_names=="fixing steepness at 0.4")]`% and `r sens_base_ssb[which(mod_names=="fixing steepness at 0.798 (2015 assessment value)")]`% for steepness at 0.4 and 0.798, respectively) and increasing equilibrium yield at a SPR50% reference harvest rate slightly. Fixing steepness at a value of 0.4 resulted in low recruitment deviations in the 2019-2024 period relative to other tested models and the base model. 

Forcing asymptotic selectivity on the midwater fleet increased estimated biomass in 2025 by `r sens_base_ssb[which(mod_names=="forcing asymptotic selectivity on the midwater trawl fleet")]`% compared to base model, while forcing logistic selectivity on the NWFSC WCGBT resulted in similar estimated spawning biomass to the base model. Including shrimp trawl data and updating WA catch reconstruction had no almost impact on the estimated spawning biomass. Excluding the triennial survey data lead to slight increases in estimated spawning biomass. 

The alternative weighting using the Francis method generally increased the estimate of spawning biomass across the timeseries, but the estimated biomass for 2025 was similar between the Francis weighted model and the base model (`r sens_base_ssb[which(mod_names=="weighting the composition data using the Francis method")]`% compared to base model). 

### Retrospective Analysis

<!-- Retrospective analysis, where the model is fitted to a series of shortened input data sets, with the most recent years of input data being dropped.  -->
 
<!-- Historical analysis (plot of actual estimates from current and previous assessments).  -->

A 5-year retrospective analysis was conducted by running the model using data only through 2020, 2021, 2022, 2023, and 2024 progressively (Table 30 and Figure 66). The initial scale of the spawning population was basically unchanged for all of these retrospectives. Removing 4–5 years of data led to slightly lower estimates of fishing mortality (F) and slightly higher spawning biomass over the last 15 years. In contrast, removing only 1–2 years resulted in higher F and lower biomass estimates. Despite these minor differences, all retrospectives showed a consistent declining trend in spawning biomass over the past decade. No concerning patterns were observed in the retrospective analysis.

### Likelihood Profiles and key parameters

<!-- Evaluation of model parameters. Likelihood profile for the base model over key parameters (typically natural morality, stock-recruit steepness, and equilibrium recruitment, or R0). The profile should indicate all likelihood values for individual components (e.g., indices by survey, compositional data for each type and fleet).   -->

Likelihood profiles were conducted for R0, steepness (even though it was not estimated in the base case) and over male and female natural mortality values simultaneously. These likelihood profiles were conducted by fixing the parameter at specific values and removing the prior on the parameter being profiled. Without the original prior distribution the MLE estimates from the base case will likely be different than the MLE in the likelihood profile, but this displays what information the data have. There was some difficulty in achieving model convergence for many parameterizations in the likelihood profile. In some cases jittering was required. 

As R0 increased, natural mortality also increased and the relative spawning biomass in 2015 was less depleted (Table 31). There was variable support for each likelihood component across the range of R0 evaluated. The total likelihood supported the estimated value (Table 31). Profiles are illustrated in Figure 68.

## Unresolved Problems and Major Uncertainties

<!-- Describe any special issues (e.g., unbalanced or questionable data, missing survey data) that complicate scientific assessment, questions about the best model scenario. -->
