# Tables 

## Data

### Fishery-dependent data

```{r} 
#| label: 'set-rda-dir-tbls'
#| echo: false 
#| warning: false 
#| eval: true 
#| include: false
library(flextable)

# You can save tables to read in as csv or rda files.
# stockplotr generally uses rda files.
# I (Kiva) prefer csv files because they are text files that are easier to track and preview with version control.

# There are many ways to incorporate tables into quarto documents.
# One is using the flextable package via R chunks.
# For help: https://ardata-fr.github.io/flextable-book/

port_tab_style <- function(ft, wd = 1) {
  ft %>% 
  font(fontname = "Times New Roman", part = "all") %>%
  fontsize(size = 9, part = "all") %>% 
  bold(part="header") %>%
  hline(part="header") %>%
  hline_top(part="header") %>% hline_bottom() %>%
  align(align = "center", part = "header") %>%
  align(align = "center", part = "body") %>%
  width(width = wd)
}

land_tab_style <- function(ft, wd = 0.6) {
  ft %>% 
  font(fontname = "Times New Roman", part = "all") %>%
  fontsize(size = 9, part = "all") %>% 
  bold(part="header") %>%
  hline(part="header") %>%
  hline_top(part="header") %>% hline_bottom() %>%
  align(align = "center", part = "header") %>%
  align(align = "center", part = "body") %>%
  width(width = wd)
}

``` 

```{r}
#| label: tbl-all_removals
#| echo: false
#| warning: false
#| tbl-cap: "Landings for bottom trawl, midwater trawl, net, and hook-and-line (mt) fisheries from Washington, Oregon, and California."

library(flextable)
library(dplyr)
library(tidyr)
library(officer)

table1 <- read.csv(here::here("report", "tables", "landings_nonhake.csv"))

st_line <- vapply(names(table1)[-1], \(x) strsplit(x, split = "_")[[1]][1], character(1), USE.NAMES = FALSE)
flt_line <- vapply(names(table1)[-1], \(x) strsplit(x, split = "_")[[1]][2], character(1), USE.NAMES = FALSE)
flt_line <- ifelse(flt_line == "Hook.and.Line", gsub(".", "-", flt_line, fixed = TRUE), gsub(".", " ", flt_line, fixed = TRUE))

# Build header map (multi-row header)
header_df <- data.frame(keys = names(table1), line1 = c("Year", flt_line), line2 = c(" ", st_line))

# my_border <- fp_border(color = "black", width = 2)

# Create flextable
flextable(table1, col_keys = names(table1)) %>%
 set_header_df(mapping = header_df, key = "keys") %>%
 merge_h(part = "header") %>%
 # merge_v(part = "header") %>%
 # border(part = "all") %>%
 # align(align = "center", part = "all") %>%
 # font(fontname = "Times New Roman", part = "all") %>%
 # bold(part = "header")%>%
 # border(border.top = my_border, i = 1) %>% 
 # border(border.top = my_border, part= "header") %>% 
 colformat_num(j = 1, big.mark = "", digits = 0) %>% 
  colformat_num(j = 2:ncol(table1), digits = 1) %>%
  port_tab_style(wd = 0.45)

```

{{< pagebreak >}}

```{r}
#| label: tbl-hake_removals
#| echo: false
#| warning: false
#| tbl-cap: "Catch (mt) from the foreign & domestic at-sea fleet and the domestic shoreside hake fleet. Catches (mt) from the Pacific whiting at-sea fishery as determined by onboard observers."

#table 2
library(flextable)
library(dplyr)
library(tidyr)

table2 <- read.csv(here::here("report", "tables", "landings_hake.csv"))

colnames(table2) <- gsub("\\.", " ", colnames(table2))

# Build header map (multi-row header)
header_df <- data.frame(
 keys = names(table2),
 line1 = c("Year", "Foreign & Domestic", rep("Shoreside hake", 3)),
 line2 = c("", "At-sea", "CA", "OR", "WA"),
 stringsAsFactors = FALSE
)

# Create flextable
flextable(table2, col_keys = names(table2)) %>%
 set_header_df(mapping = header_df, key = "keys") %>%
 merge_h(part = "header") %>%
 # merge_v(part = "header") %>%
 # border(part = "all") %>%
 colformat_num(j = 1, big.mark = "", digits = 0) %>%
 port_tab_style(wd = 0.8)
 # align(align = "center", part = "all") %>%
 # font(fontname = "Times New Roman", part = "all") %>%
 # bold(part = "header")%>%
 # autofit()

```

<!-- {{< pagebreak >}} -->

<!-- ```{r} -->
<!-- #| label: tbl-manage-act -->
<!-- #| echo: false -->
<!-- #| warning: false -->
<!-- #| tbl-cap: "A subset of management actions of importance to fisheries that caught widow rockfish." -->

<!-- #table 3 -->

<!-- library(flextable) -->
<!-- library(dplyr) -->
<!-- library(tidyr) -->
<!-- ManageTable<- read.csv(file.path(here::here(),"report/tables/Table_3_2025.csv")) -->
<!-- colnames(ManageTable) <- c("Year","Management action") -->

<!-- ManageTable<- ManageTable %>% -->
<!--  group_by(Year)%>% -->
<!--  ungroup() -->
<!--  # mutate(Year_Display = ifelse(row_number() == 1, as.character(Year), "")) %>% -->

<!-- flextable(ManageTable) %>% -->
<!--  set_header_labels(Year = "Year", `Management action` = "Management action") %>% -->
<!--  merge_v(j = "Year") %>% -->
<!--  align(j = "Year", align = "center", part = "all") %>% -->
<!--  align(j = "Management action", align = "left", part = "all") %>% -->
<!--  font(fontname = "Times New Roman", part = "all") %>%  -->
<!--  fontsize(size = 9, part = "all") %>% -->
<!--  bold(part= "header") %>%  -->
<!--  border_outer(part = "all") %>% -->
<!--  border_inner(part = "all") %>% -->
<!--  colformat_num(j = 1, big.mark = "", digits = 0) %>% -->
<!--  flextable::width(j = "Year", width = 0.7) %>% # Year column width -->
<!--  flextable::width(j = "Management action", width = 5)  # Management action column width -->

<!-- # select(-ComModelTotal) -->
<!-- # CatchTable[is.na(CatchTable)] <- 0 -->
<!-- # CatchTable |> -->
<!-- # gt() |> -->
<!-- # cols_label( -->
<!-- #  year = "Year", -->
<!-- #  ComWA = "Com. WA", -->
<!-- #  ComOR = "Com. OR", -->
<!-- #  ComCA = "Com. CA", -->
<!-- #  ComDiscards = "Com. Discards", -->
<!-- #  Foreign = "For.", -->
<!-- #  RecWA = "Rec. WA", -->
<!-- #  RecOR = "Rec. OR", -->
<!-- #  RecCA = "Rec. CA", -->
<!-- #  ) |>  -->
<!-- #  tab_options( -->
<!-- #  table.font.size = 12, -->
<!-- #  latex.use_longtable = TRUE -->
<!-- #  ) |> -->
<!-- #  as_latex() -->

<!-- ``` -->

{{< pagebreak >}}

```{r}
#| label: tbl-manage-guide
#| echo: false
#| warning: false
#| tbl-cap: "Management guidelines for widow rockfish from 2004 to 2024. Total landings (mt) are also shown."

#Table 4

library(flextable)
library(dplyr)
library(tidyr)

#table4_data <- as.data.frame(read.csv(file.path(here::here(),"report/tables/exec_summ_tables/f_Manage_ES.csv"), stringsAsFactors = FALSE))

table4_data <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table4.csv"), stringsAsFactors = FALSE))
colnames(table4_data) <- gsub("\\.", " ", colnames(table4_data))

flextable(table4_data) %>%
 # Set header labels
 set_header_labels(names = colnames(table4_data), 
                   values = c("Year",
                              "OFL (mt) (termed ABC prior to 2011)",
                              "ABC (mt)",
                              "ACL (mt)\n(termed OY\nprior to 2011)",
                              "Commercial\nLandings (mt)",
                              "Estimated Total\nCatch (mt)")) %>%
 # # Apply borders
 # border(part = "all", border = officer::fp_border(color = "black", width = 1)) %>%
 # # Align header and body
 # align(align = "center", part = "header") %>%
 # align(align = "right", part = "body", j = -1) %>%
 # # Bold header
 # bold(part = "header") %>%
 # # Set font
 # font(fontname = "Times New Roman", part = "all") %>%
 colformat_num(j = 1, big.mark = "", digits = 0) %>% port_tab_style(wd=1)

```

{{< pagebreak >}}

{{< pagebreak >}}
\blandscape
```{r}
#| label: tbl-num-land-length
#| echo: false
#| warning: false
#| tbl-cap: "Number of trips sampled for length data by gear and state for non-whiting fisheries."

#Old table 10

table10 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table_10.csv"), stringsAsFactors = FALSE))
#Remove periods
colnames(table10) <- gsub("\\.", " ", colnames(table10))

# Build header map (multi-row header)
header_df <- data.frame(
 keys = names(table10),
 line1 = c("","Year", rep("Bottom Trawl", 3), rep("Midwater Trawl", 3),rep("Net", 2),rep("Hook-and-Line", 3)),
 line2 = c(" "," ", "CA", "OR", "WA", "CA", "OR", "WA", "CA", "WA", "CA", "OR", "WA"),
 stringsAsFactors = FALSE
)

# Create flextable
flextable(table10, col_keys = names(table10)) %>%
  set_header_df(mapping = header_df, key = "keys") %>%
 delete_columns(j = 1) %>%
 merge_h(part = "header") %>%
 # merge_v(part = "header") %>%
 # border(part = "all") %>%
 # align(align = "center", part = "all") %>%
 # font(fontname = "Times New Roman", part = "all") %>%
 # bold(part = "header")%>%
 # autofit() %>%
 colformat_num(j = 1, big.mark = "", digits = 0) %>%
 land_tab_style(wd=0.6)

```

```{r}
#| label: tbl-len-gear-state
#| echo: false
#| warning: false
#| tbl-cap: "Number of lengths of widow rockfish by gear and state for non-whiting fisheries."

#Old table 11
table11 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table_11.csv"), stringsAsFactors = FALSE))

# Build header map (multi-row header)
header_df <- data.frame(
 keys = names(table10),
 line1 = c("","Year", rep("Bottom Trawl", 3), rep("Midwater Trawl", 3),rep("Net", 2),rep("Hook-and-Line", 3)),
 line2 = c(" "," ", "CA", "OR", "WA", "CA", "OR", "WA", "CA", "WA", "CA", "OR", "WA"),
 stringsAsFactors = FALSE
)

# Create flextable
flextable(table11, col_keys = names(table11)) %>%
 set_header_df(mapping = header_df, key = "keys") %>%
 delete_columns(j = 1) %>%
 merge_h(part = "header") %>%
 # merge_v(part = "header") %>%
 # border(part = "all") %>%
 # align(align = "center", part = "all") %>%
 # font(fontname = "Times New Roman", part = "all") %>%
 # bold(part = "header")%>%
 # autofit() %>%
 colformat_num(j = 1, big.mark = "", digits = 0) %>%
 land_tab_style(wd=0.6)

```
\elandscape
```{r}
#| label: tbl-landings-hake
#| echo: false
#| warning: false
#| tbl-cap: "Number of hauls or trips and number of lengths sampled from the at-sea hake and shoreside hake fisheries."

#Old table 12
table12 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table_12.csv"), stringsAsFactors = FALSE))

# Build header map (multi-row header)
header_df <- data.frame(
 keys = names(table12),
 line1 = c("","Year", rep("Number of hauls (at-sea) or landings (shoreside)", 2), rep("Number of lengths", 2)),
 line2 = c(" "," ","Domestic at-sea", "Shoreside","Domestic at-sea", "Shoreside" ),
 stringsAsFactors = FALSE
)

# Create flextable
flextable(table12, col_keys = names(table12)) %>%
 set_header_df(mapping = header_df, key = "keys") %>%
 delete_columns(j = 1) %>%
 merge_h(part = "header") %>%
 # merge_v(part = "header") %>%
 # border(part = "all") %>%
 # align(align = "center", part = "all") %>%
 # font(fontname = "Times New Roman", part = "all") %>%
 # bold(part = "header")%>%
 # autofit() %>%
 colformat_num(j = 1, big.mark = "", digits = 0) %>%
 port_tab_style(wd=0.75)

```

{{< pagebreak >}}
\blandscape
```{r}
#| label: tbl-sample-age-gear-state
#| echo: false
#| warning: false
#| tbl-cap: "Number of landings sampled for ages by gear and state for non-whiting fisheries."

#Old table 13
table13 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table_13.csv"), stringsAsFactors = FALSE))

# Build header map (multi-row header)
header_df <- data.frame(
 keys = names(table13),
 line1 = c("","Year", rep("Bottom Trawl", 3), rep("Midwater Trawl", 3),rep("Net", 2),rep("Hook-and-Line", 3)),
 line2 = c(" "," ", "CA", "OR", "WA", "CA", "OR", "WA", "CA", "WA", "CA", "OR", "WA"),
 stringsAsFactors = FALSE
)

# Create flextable
flextable(table13, col_keys = names(table13)) %>%
 set_header_df(mapping = header_df, key = "keys") %>%
 delete_columns(j = 1) %>%
 merge_h(part = "header") %>%
 # merge_v(part = "header") %>%
 # border(part = "all") %>%
 # align(align = "center", part = "all") %>%
 # font(fontname = "Times New Roman", part = "all") %>%
 # bold(part = "header")%>%
 # autofit() %>%
 colformat_num(j = 1, big.mark = "", digits = 0) %>%
 land_tab_style(wd=0.6)

```

```{r}
#| label: tbl-age-gear-state
#| echo: false
#| warning: false
#| tbl-cap: "Number of landings sampled for ages by gear and state for non-whiting fisheries."

#Old table 13
table14 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table_14.csv"), stringsAsFactors = FALSE))

# Build header map (multi-row header)
header_df <- data.frame(
 keys = names(table14),
 line1 = c("","Year", rep("Bottom Trawl", 3), rep("Midwater Trawl", 3),rep("Net", 2),rep("Hook-and-Line", 3)),
 line2 = c(" "," ", "CA", "OR", "WA", "CA", "OR", "WA", "CA", "WA", "CA", "OR", "WA"),
 stringsAsFactors = FALSE
)

# Create flextable
# Create flextable
flextable(table14, col_keys = names(table14)) %>%
 set_header_df(mapping = header_df, key = "keys") %>%
 delete_columns(j = 1) %>%
 merge_h(part = "header") %>%
 # merge_v(part = "header") %>%
 # border(part = "all") %>%
 # align(align = "center", part = "all") %>%
 # font(fontname = "Times New Roman", part = "all") %>%
 # bold(part = "header")%>%
 # autofit() %>%
 colformat_num(j = 1, big.mark = "", digits = 0) %>%
 land_tab_style(wd=0.6)

```

```{r}
#| label: tbl-disc-totals
#| echo: false
#| warning: false
#| tbl-cap: "Discard totals (mt) for four fleets derived from Pikitch data, EDCP data, and WCGOP data. Italics indicate years that were not fitted to because they were simply added to the landings (Shoreside hake) or omitted because they were outside of the main study period."

#Old table 16

table16 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table_16_data.csv"), stringsAsFactors = FALSE))
#Remove periods
colnames(table16) <- gsub("\\.", " ", colnames(table16))

# Function for consistent table styling
# style_table16 <- function(ft) {
#  ft %>%
#  font(fontname = "Times New Roman", part = "all") %>%
#  border_outer(part = "all") %>%
#  border_inner(part = "all") %>%
#  align(align = "center", part = "header") %>%
#  align(align = "center", part = "body")%>%
#  colformat_num(j = 2, big.mark = "", digits = 0)%>%
#  autofit()
# }

# Create Flextable for Table 20
table16 %>%
 flextable() %>%
 colformat_num(j = 2, big.mark = "", digits = 0) %>%
 # style_table16()
 port_tab_style(wd=0.9)

```
\elandscape

### Fishery-independent data

```{r}
#| label: tbl-depth-surv
#| echo: false
#| warning: false
#| tbl-cap: "Depth ranges and limits of the southern latitude in the Triennial survey for the different years."

#Old table 6

library(flextable)
library(dplyr)
library(tidyr)

table6_data <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table6.csv"), stringsAsFactors = FALSE))

# # Function for consistent table styling
# style_flextable <- function(ft) {
#  ft %>%
#  font(fontname = "Times New Roman", part = "all") %>%
#  border_outer(part = "all") %>%
#  border_inner(part = "all") %>%
#  align(align = "center", part = "header") %>%
#  align(align = "center", part = "body")
# }

# Create Flextable for Table 6
table6_data %>%
 flextable() %>%
 set_header_labels(
   Years = "Years",
   Depth_range_m = "Depth range (m)",
   Southern_latitude = "Southern latitude") %>%
 port_tab_style(wd = 1.5)

```


```{r}
#| label: tbl-strat-surv
#| echo: false
#| warning: false
#| tbl-cap: "Stratifications used for the two surveys."

library(flextable)
library(dplyr)
library(tidyr)

table7_nwfsc_data <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table7_nwfsc.csv"), stringsAsFactors = FALSE))

table7_triennial_data <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table7_triennial.csv"), stringsAsFactors = FALSE))

# Function for consistent table styling
# style_flextable <- function(ft) {
#  ft %>%
#  font(fontname = "Times New Roman", part = "all") %>%
#  border_outer(part = "all") %>%
#  border_inner(part = "all") %>%
#  align(align = "center", part = "header") %>%
#  align(align = "center", part = "body")
# }

# Create Flextable for Table 7 (Triennial)
table7_triennial_data %>%
 flextable() %>%
 set_header_labels(Strata = "Strata",
                   Area_km2 = "Area (km2)",
                   Depth1 = "Depth1",
                   Depth2 = "Depth2",
                   Latitude1 = "Latitude1",
                   Latitude2 = "Latitude2") %>%
 add_header_row(values = c("Triennial"), colwidths = 6) %>%
 # style_flextable()
 port_tab_style(wd=0.8)

# Create Flextable for Table 7 (NWFSC WCGBT)
table7_nwfsc_data %>%
 flextable() %>%
 set_header_labels(Strata = "Strata",
                   Area_km2 = "Area (km2)",
                   Depth1 = "Depth1",
                   Depth2 = "Depth2",
                   Latitude1 = "Latitude1",
                   Latitude2 = "Latitude2") %>%
 add_header_row(values = c("NWFSC WCGBT"), colwidths = 6) %>%
 # style_flextable()
 port_tab_style(wd=0.8)

```

{{< pagebreak >}}

```{r}
#| label: tbl-numposi-tows
#| echo: false
#| warning: false
#| tbl-cap: "Number of positive tows, lengths, and ages in each year from the Triennial survey (Tri) and the NWFSC WCGBT survey (NW)."
#| width: 80%

#Old table 9
table9 <- as.data.frame(read.csv(file.path(here::here(),"figures/WCGBTS_survey/survey_pos_catch.csv"), stringsAsFactors = FALSE))
# remove extra rows
table9 <- table9[rowSums(is.na(table9[, 2:ncol(table9)])) != ncol(table9[, 2:ncol(table9)]),]

# Build header map (multi-row header)
header_df <- data.frame(
 keys = names(table9),
 line1 = c("Year", rep("Number of positive tows", 2), rep("Number of tows with lengths", 2), rep("Number of lengths", 2),rep("Number of tows with ages", 2),rep("Number of ages", 2)),
 line2 = c("","Tri","NW", "Tri","NW", "Tri","NW", "Tri","NW", "Tri","NW"),
 stringsAsFactors = FALSE
)

# Create flextable
flextable(table9, col_keys = names(table9)) %>%
 set_header_df(mapping = header_df, key = "keys") %>%
 merge_h(part = "header") %>%
 # merge_v(part = "header") %>%
 # border(part = "all") %>%
 # align(align = "center", part = "all") %>%
 # font(fontname = "Times New Roman", part = "all") %>%
 # bold(part = "header")%>%
 # autofit() %>%
 colformat_num(j = 1, big.mark = "", digits = 0) %>%
 port_tab_style(wd=0.45)

```

```{r}
#| label: tbl-age-error
#| echo: false
#| warning: false
#| tbl-cap: "Ageing error for two labs that was used in the assessment model."

#Old table 20

library(flextable)
library(dplyr)
library(tidyr)
library(officer)

table20<- as.data.frame(read.csv(file.path(here::here(),"report/tables/table20.csv"), stringsAsFactors = FALSE))

# Function for consistent table styling
# style_table20 <- function(ft) {
#  ft %>%
#   font(fontname = "Times New Roman", part = "all") %>%
#   border_outer(part = "all") %>%
#   border_inner(part = "all") %>%
#   align(align = "center", part = "header") %>%
#   align(align = "center", part = "body")
# }

# Create Flextable for Table 20
table20 %>%
 flextable() %>%
 set_header_labels(
  True.Age = "True Age",
  Standard.Deviation.CAP = "Standard Deviation CAP",
  Standard.Deviation.SWFSC = "Standard Deviation SWFSC"
 ) %>%
 port_tab_style(wd=1.5)

```

## Model results

```{r}
#| label: tbl-speci-base-assess
#| echo: false
#| warning: false
#| tbl-cap: "Specifications of the base assessment model for widow rockfish."

#Old table 21

library(flextable)
library(dplyr)
library(tidyr)
library(officer)

table21<- as.data.frame(openxlsx::read.xlsx(file.path(here::here(),"report/tables/table_21.xlsx")))
colnames(table21) <- c("1","2","3")

table21$`2`[which(table21$`2`=="Minimum ages for first growth calcs")] <- "First reference age for growth calcs"
table21$`2`[which(table21$`2`=="Maximum ages for first growth calcs")] <- "Second reference age for growth calcs"
table21$`2`[which(table21$`2`=="Satrting year of estimated recruitment")] <- "Starting year of estimated recruitment"

rmv_rows <- c("Fishery timing", "Triennial survey timing", "NWFSC WCGBT survey timing", "Fishing mortality methods", "maximum F")
table21 <- table21 %>% filter(! `2` %in% rmv_rows)

my_border <- fp_border(color = "black", width = 2)

flextable(table21) %>%
 delete_part(part="header")%>%
 border(part = "all") %>%
 align(align = "left", j=2) %>%
 italic(j = 1, italic = TRUE)%>%
 font(fontname = "Times New Roman", part = "all") %>%
 bold(part = "header")%>%
 border(border.top = my_border, i = 1) %>%
 autofit() %>%
 colformat_num(j = 1, big.mark = "", digits = 0)%>%
 fontsize(size = 9, part = "all")%>%
 set_table_properties(layout = "autofit")

```


```{r}
#| label: tbl-bio-params
#| echo: false
#| warning: false
#| tbl-cap: "Description of biological parameters in the base case assessment model. The lognormal (LN) prior distribution is specified with the median of the parameter and the standard deviation of the log of the parameter."

#Old table 22

# Function for consistent table styling
table22 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table_22.csv"))) 
table22 <- table22[,2:ncol(table22)] 
my_border <- fp_border(color = "black", width = 2) 
# Build header map (multi-row header) 
header_df <- data.frame( keys = names(table22), 
            line1 = c("", "Initial", "Number", "Bounds","Prior"), 
            line2 = c("Parameter", "value", "estimated", "(low, high)", "distribution"), stringsAsFactors = FALSE ) 

## Fix latex error
table22$Parameter[table22$Parameter == "Natural Mortality (M) yr^-1"] <- "Natural Mortality (M) yr-1"

# Function for consistent table styling 
flextable(table22) %>%  
 set_header_labels(names=colnames(table22), values = c("Parameter", "Initial value", "Number estimated", "Bounds (low, high)", "Prior distribution")) %>%
 # set_header_df(mapping = header_df, key = "keys") %>% 
 port_tab_style (wd=0.85) %>%
 bold(i = c(1, 14)) %>% hline(i = c(1, 13, 14))
 # border(part = "all") %>% align(align = "left", j=2) %>% 
 # font(fontname = "Times New Roman", part = "all") %>% 
 # bold(part = "header")%>% border(border.top = my_border, i = 1) %>% 
 # autofit() %>% 
 # colformat_num(j = 1, big.mark = "", digits = 0)%>% 
 # fontsize(size = 9, part = "all")%>% 
 # set_table_properties(layout = "autofit")

```
\blandscape
```{r}
#| label: tbl-param-ests-basecase
#| echo: false
#| warning: false
#| tbl-cap: "Description of biological parameters in the base case assessment model. The lognormal (LN) prior distribution is specified with the median of the parameter and the standard deviation of the log of the parameter."

#Old table 23

# Function for consistent table styling
table23 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table_23.csv"))) 
colnames(table23) <- c(" ","Parameter", "Estimate", "SD")

# table23
# my_border <- fp_border(color = "black", width = 2) 
# Build header map (multi-row header) 
# header_df <- data.frame( keys = names(table23), 
#             line1 = c("", "Initial", "Number", "Bounds","Prior"), 
#             line2 = c("Parameter", "value", "estimated", "(low, high)", "distribution"), stringsAsFactors = FALSE ) 
# Function for consistent table styling 

flextable(table23) %>% land_tab_style(wd=1.6) %>%
 #set_header_df(mapping = header_df, key = "keys") %>% 
 # border(part = "all") %>% 
 align(align = "left", j=2) %>% 
 # font(fontname = "Times New Roman", part = "all") %>% 
 # italic(i=c(3,17,25), italic=TRUE)%>%
 bold(i=c(3,17,25)) %>% hline(i = c(2, 3, 16, 17, 24, 25))
 # bold(part = "header")%>% border(border.top = my_border, i = 1) %>% 
 # autofit() %>% 
 # colformat_num(j = 1, big.mark = "", digits = 0) #%>% 
 # fontsize(size = 9, part = "all")%>% 
 # set_table_properties(layout = "autofit")

```

```{r}
#| label: tbl-param-ests-select
#| echo: false
#| warning: false
#| tbl-cap: "Parameter estimates and approximate asymptotic standard deviations for the base case model selectivity parameters. "

#Old table 24

# Function for consistent table styling
table24 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table_24.csv"))) 
colnames(table24) <- gsub("\\.", " ", colnames(table24))
# manually round bc way too many digits
table24$Estimate <- round(table24$Estimate, 3)
table24$SD <- round(table24$SD, 3)

# my_border <- fp_border(color = "black", width = 2) 

# Function for consistent table styling 
flextable(table24) %>% port_tab_style(wd=1.5) %>%
 # border(part = "all") %>% 
 align(align = "left", j=1) %>% 
 # font(fontname = "Times New Roman", part = "all") %>% 
 # bold(part = "header")%>% border(border.top = my_border, i = 1) %>% 
 # autofit() %>% 
 colformat_num(j = ncol(table24), big.mark = "", digits = 0) # %>% 
 # set_table_properties(layout = "autofit")

```
\elandscape
```{r}
#| label: tbl-likecomps
#| echo: false
#| warning: false
#| tbl-cap: "Likelihood components and other quantities related to the minimization of the base case model."

#Old table 25

# Function for consistent table styling
table25 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table_25.csv"))) 
# rounding up front
table25$Values <- round(table25$Values, 3)

# my_border <- fp_border(color = "black", width = 2) 

# Function for consistent table styling 
flextable(table25) %>% 
  bold(i = 3) %>% hline(i = c(2, 3)) %>%
  port_tab_style(wd=2) %>% 
  align(align = c("left", "right"), part = "all") %>%
  colformat_num(i = 1, j = 2, digits = 0) 
 # border(part = "all") %>% 
 # font(fontname = "Times New Roman", part = "all") %>% 
 # bold(part = "header")%>% 
 # italic(i=3,italic=TRUE)%>%
 # border(border.top = my_border, i = 1) %>% 
 # fontsize(size = 9, part = "all")%>% 
 # set_table_properties(layout = "autofit")

```

```{r}
#| label: tbl-key-deriv-params
#| echo: false
#| warning: false
#| tbl-cap: "Estimates of key derived parameters and reference points with approximate 95% asymptotic confidence intervals."

#Old table 26

# Function for consistent table styling
table26 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/exec_summ_tables/e_ReferencePoints_ES.csv"), header = F)) 
table26[1, 2:ncol(table26)] <- ""

my_border <- fp_border(color = "black", width = 2)

colnames(table26) <- c("Value", "Estimate", "Lower Interval", "Upper Interval")# gsub("\\.", " ", colnames(table26))

table26 <- table26 %>%
 mutate(
  `~95% Confidence Interval` = paste0(`Lower Interval`, " - ", `Upper Interval`)
 ) %>%
 # Remove the original "Lower Interval" and "Upper Interval" columns
 select(-`Lower Interval`, -`Upper Interval`)

table26[6,3] <- " "
table26[11,3] <- " "
table26[16,3] <- " "

# Function for consistent table styling 
flextable(table26) %>% land_tab_style(wd=1.9) %>%
 # border(part = "all") %>% 
 # font(fontname = "Times New Roman", part = "all") %>% 
 # bold(part = "header")%>% 
 # align(align = "center", j = c(2,3))%>% 
 # italic(i=c(6,11,13,16),italic=TRUE)%>%
 bold(i=c(1,7,11,17),bold=TRUE)%>% hline(i = c(1,6,7,11,12,16,17)) %>%
 align(j = 1, align = "left", part = "all")
 # border(border.top = my_border, i = 1) %>% 
 # fontsize(size = 9, part = "all")%>% 
 # set_table_properties(layout = "autofit")

```
\blandscape
```{r}
#| label: tbl-ts-popests-basecase
#| echo: false
#| warning: false
#| tbl-cap: "Time series of population estimates from the base case model."

#Old table 27

# Function for consistent table styling
table27 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table_27.csv"))) 
# build in rounding
table27$SpawningDepletion... <- round(table27$SpawningDepletion..., 3)
table27$X1..SPR... <- round(table27$X1..SPR..., 3)
table27$Relative.exploitation.rate.... <- round(table27$Relative.exploitation.rate...., 3)
table27$Age.0.recruits <- round(table27$Age.0.recruits, 1)
table27$Estimated.Total.Catch.mt. <- round(table27$Estimated.Total.Catch.mt., 1)

# my_border <- fp_border(color = "black", width = 2)

# Build header map (multi-row header) 
# header_df <- data.frame( keys = names(table27), 
#             line1 = c("Year", "Total", "Spawning", "Age 4+ ", "Spawning", "Age-0", "Estimated Total", "1 - SPR", "Relative Exploitation"), 
#             line2 = c(" ", "Biomass (mt)", "Biomass (mt)","Biomass (mt)", " Depletion(mt)", "recruits", "Catch (mt)","(%)","rate (%)"), stringsAsFactors = FALSE ) 


# Function for consistent table styling 
flextable(table27) %>% 
 set_header_labels(names = colnames(table27), 
                  values = c("Year", 
                             "Total biomass (mt)", 
                             "Spawning biomass (mt)", 
                             "Age 4+ biomass (mt)", 
                             "Spawning depletion (mt)", 
                             "Age-0 recruits (number)", 
                             "Estiamted total catch (mt)", 
                             "1-SPR (%)", 
                             "Relative exploitation rate (%)")) %>%
 # set_header_df(mapping = header_df, key = "keys") %>% 
 port_tab_style(wd=1.2) %>%
 # border(part = "all") %>% 
 # font(fontname = "Times New Roman", part = "all") %>% 
 # bold(part = "header")%>% 
 # align(align = "center", part="body")%>% 
 # align(align = "center", part="header")%>% 
 # border(border.top = my_border, i = 1) %>% 
 # fontsize(size = 9, part = "all")%>% 
 # set_table_properties(layout = "autofit")%>%
 colformat_num(j = 1, big.mark = "", digits = 0) %>% 
 width(width = 0.85)


```
<!-- \elandscape -->
<!-- ```{r} -->
<!-- #| label: tbl-lognorm-recdevs -->
<!-- #| echo: false -->
<!-- #| warning: false -->
<!-- #| tbl-cap: "Time series of log-normal recruitment deviation estimates from the base case model." -->

<!-- #Old table 28 -->

<!-- # Function for consistent table styling -->
<!-- table28 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/table_28.csv")))  -->

<!-- my_border <- fp_border(color = "black", width = 2) -->

<!-- colnames(table28) <- gsub("\\.", " ", colnames(table26)) -->

<!-- # Function for consistent table styling  -->
<!-- flextable(table28) %>% port_tab_style(wd=1.5) %>% -->
<!--  # border(part = "all") %>%  -->
<!--  # font(fontname = "Times New Roman", part = "all") %>%  -->
<!--  # bold(part = "header")%>%  -->
<!--  # align(align = "center", j = c(2,3))%>%  -->
<!--  colformat_num(j = 1, big.mark = "", digits = 0) #%>% -->
<!--  # border(border.top = my_border, i = 1) %>%  -->
<!--  # fontsize(size = 9, part = "all")%>%  -->
<!--  # set_table_properties(layout = "autofit") -->

<!-- ``` -->

{{< pagebreak >}}
<!-- \blandscape -->
```{r}
#| label: tbl-quant-sens-int
#| echo: false
#| warning: false
#| tbl-cap: "Quantities of interest from the sensitivity analyses."

#Old table 29
#needs to be landscape! 

library(flextable)
library(dplyr)
library(tidyr)
library(officer)

table29 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/short_sens_table.csv"), stringsAsFactors = FALSE))
#Remove periods
colnames(table29) <- c(" ", "Base model", "M = 0.1", "M = 0.124 female, M = 0.129 male",
           "MWT asymptotic selex", "WCGBTS logistic selex", 
           "Including shrimp trawl", "New WA catch recon.", 
           # "h = 0.4", "h = 0.6", "h = 0.798", 
           "Excluding triennial", "Francis weighting")
 # gsub("\\.", " ", colnames(table29))


# Function for consistent table styling
# style_table29 <- function(ft) {
#  ft %>%
#   font(fontname = "Times New Roman", part = "all") %>%
#   border_outer(part = "all") %>%
#   bold(part = "header") %>%
#   fontsize(size = 9, part = "all") %>%   
#   colformat_num(digits = 3) %>%
#   # border_inner(part = "all") %>%
#   align(align = "center", part = "header") %>%
#   align(align = "center", part = "body")
# }

likelihood_row <- which(apply(table29, 1, function(row) any(row == "LIKELIHOOD")))
parameter_row <- which(apply(table29, 1, function(row) any(row == "PARAMETER")))
quantity_row <- which(apply(table29, 1, function(row) any(row == "QUANTITY")))

# Add a row that spans all columns (like a section header)
 flextable(table29) %>% land_tab_style(wd=0.7) %>% colformat_num(i = 15, j = 1:ncol(table29), digits = 0) %>%
 compose(i = likelihood_row, j = 1, value = as_paragraph("Difference from Base Model Likelihood")) %>%
 merge_at(i = likelihood_row, j = 1:ncol(table29), part = "body") %>%
 align(i = likelihood_row, j = 1:ncol(table29), align = "center", part = "body") %>%
 bold(i = likelihood_row, part = "body") %>% hline(i = c(likelihood_row)) %>% 
   compose(i = parameter_row, j = 1, value = as_paragraph("Parameter values")) %>%
 merge_at(i = parameter_row, j = 1:ncol(table29), part = "body") %>%
 align(i = parameter_row, j = 1:ncol(table29), align = "center", part = "body") %>%
 bold(i = parameter_row, part = "body") %>% hline(i = c(parameter_row-1, parameter_row)) %>% 
  compose(i = quantity_row, j = 1, value = as_paragraph("Quantity")) %>%
 merge_at(i = quantity_row, j = 1:ncol(table29), part = "body") %>%
 align(i = quantity_row, j = 1:ncol(table29), align = "center", part = "body") %>%
 bold(i = quantity_row, part = "body") %>% hline(i = c(quantity_row-1, quantity_row))
 
 # border(i = 1, j = 1:ncol(table29), part = "footer", border = fp_border(color = "transparent", width = 0)) %>%
 # # Keep the outer bottom border of the merged footer row
 # border(i = 1, j = 1:ncol(table29), part = "footer", border = fp_border(color = "black", width = 1))%>%
 # style_table29()%>% 
 # autofit() %>% width(width = 0.6)

```


{{< pagebreak >}}

<!-- ```{r} -->
<!-- #| label: tbl-retros -->
<!-- #| echo: false -->
<!-- #| warning: false -->
<!-- #| tbl-cap: "Results from retrospective runs, sequentially removing data over the last five years using the base case assumptions." -->

<!-- #Old table 30 -->

<!-- library(flextable) -->
<!-- library(dplyr) -->
<!-- library(tidyr) -->
<!-- library(officer) -->

<!-- table30<- read.csv(file.path(here::here(),"report/tables/retro_quant_table.csv"), stringsAsFactors = FALSE) -->
<!-- #Remove periods -->
<!-- colnames(table30) <- gsub("\\.", " ", colnames(table30)) -->

<!-- # Function for consistent table styling -->
<!-- # style_table30 <- function(ft) { -->
<!-- #  ft %>% -->
<!-- #   font(fontname = "Times New Roman", part = "all") %>% -->
<!-- #   # fontsize(size = 9) %>%  -->
<!-- #   colformat_num(digits = 3) %>% -->
<!-- #   border_outer(part = "all") %>% -->
<!-- #   bold(part="header") %>% -->
<!-- #   # border_inner(part = "all") %>% -->
<!-- #   align(align = "center", part = "header") %>% -->
<!-- #   align(align = "center", part = "body") -->
<!-- # } -->

<!-- likelihood_row <- which(apply(table30, 1, function(row) any(row == "Likelihood"))) -->

<!-- # Add a row that spans all columns (like a section header) -->
<!--  flextable(table30) %>% land_tab_style(wd=1) %>%  -->
<!--  colformat_num(i = 15, j = 1:6, digits = 0) %>% -->
<!--  colformat_num(j = 2:6, digits = 3) %>% -->
<!--  compose(i = likelihood_row, j = 1, value = as_paragraph("Difference from Base Model Likelihood")) %>% -->
<!--  merge_at(i = likelihood_row, j = 1:ncol(table30), part = "body") %>% -->
<!--  align(i = likelihood_row, j = 1:ncol(table30), align = "center", part = "body") %>% -->
<!--  bold(i = likelihood_row, part = "body") %>% hline(i = c(likelihood_row-1, likelihood_row))  -->
<!--  # compose(i = likelihood_row, j = 1, value = as_paragraph("Difference from Base Model Likelihood")) %>% -->
<!--  # merge_at(i = likelihood_row, j = 1:ncol(table30), part = "body") %>% -->
<!--  # align(i = likelihood_row, j = 1:ncol(table30), align = "center", part = "body") %>% -->
<!--  # bold(i = likelihood_row, part = "body") %>% -->
<!--  # border(i = 1, j = 1:ncol(table30), part = "footer", border = fp_border(color = "transparent", width = 0)) %>% -->
<!--  # # Keep the outer bottom border of the merged footer row -->
<!--  # border(i = 1, j = 1:ncol(table30), part = "footer", border = fp_border(color = "black", width = 1))%>% -->
<!--  # style_table30()%>% -->
<!--  # autofit() -->


<!-- ``` -->


<!-- ```{r} -->
<!-- #| label: tbl-like-R0 -->
<!-- #| echo: false -->
<!-- #| warning: false -->
<!-- #| tbl-cap: "Quantities of interest when profiling over R0 values." -->

<!-- #Old table 31 -->

<!-- table31 <- read.csv(file.path(here::here(),"report/tables/SR_LN(R0)_quant_table.csv"), stringsAsFactors = FALSE) -->
<!-- #Remove periods -->
<!-- colnames(table31) <- c("log(R0)",	"10.4","10.2","10","9.8","10.6","10.8","11","11.2","11.4") -->

<!-- # Function for consistent table styling -->
<!-- # style_table31 <- function(ft) { -->
<!-- #  ft %>% -->
<!-- #   font(fontname = "Times New Roman", part = "all") %>% -->
<!-- #   fontsize(size = 9) %>%  -->
<!-- #   bold(part = "header") %>% -->
<!-- #   colformat_num(digits = 3) %>% -->
<!-- #   border_outer(part = "all") %>% -->
<!-- #   # border_inner(part = "all") %>% -->
<!-- #   align(align = "center", part = "header") %>% -->
<!-- #   align(align = "center", part = "body") -->
<!-- # } -->

<!-- likelihood_row <- which(apply(table31, 1, function(row) any(row == "Likelihood"))) -->

<!-- # Add a row that spans all columns (like a section header) -->
<!--  flextable(table31) %>% land_tab_style(wd=0.65) %>%  -->
<!--  colformat_num(i = 15, j = 1:6, digits = 0) %>% -->
<!--  colformat_num(j = 2:6, digits = 3) %>% -->
<!--  compose(i = likelihood_row, j = 1, value = as_paragraph("Difference from Base Model Likelihood")) %>% -->
<!--  merge_at(i = likelihood_row, j = 1:ncol(table31), part = "body") %>% -->
<!--  align(i = likelihood_row, j = 1:ncol(table31), align = "center", part = "body") %>% -->
<!--  bold(i = likelihood_row, part = "body") %>% hline(i = c(likelihood_row-1, likelihood_row)) -->

<!--  # compose(i = likelihood_row, j = 1, value = as_paragraph("Difference from Base Model Likelihood")) %>% -->
<!--  # merge_at(i = likelihood_row, j = 1:ncol(table31), part = "body") %>% -->
<!--  # align(i = likelihood_row, j = 1:ncol(table31), align = "center", part = "body") %>% -->
<!--  # bold(i = likelihood_row, part = "body") %>% -->
<!--  # border(i = 1, j = 1:ncol(table31), part = "footer", border = fp_border(color = "transparent", width = 0)) %>% -->
<!--  # # Keep the outer bottom border of the merged footer row -->
<!--  # border(i = 1, j = 1:ncol(table31), part = "footer", border = fp_border(color = "black", width = 1))%>% -->
<!--  # style_table31()%>% fontsize(size = 11, i = likelihood_row) %>% -->
<!--  # autofit() %>% width(width = 0.6, j = 1:(dim(table_h)[2]-1)) -->


<!-- ``` -->


<!-- ```{r} -->
<!-- #| label: tbl-like-steep -->
<!-- #| echo: false -->
<!-- #| warning: false -->
<!-- #| tbl-cap: "Quantities of interest when profiling over steepness values." -->

<!-- #Old table 31 -->

<!-- table32 <- read.csv(file.path(here::here(),"report/tables/SR_BH_steep_quant_table.csv"), stringsAsFactors = FALSE) -->
<!-- #Remove periods -->
<!-- colnames(table32) <- c("steepness (h)","0.715","0.66","0.605","0.55","0.495","0.44","0.385","0.33","0.275","0.77","0.825",	"0.88") -->

<!-- # Function for consistent table styling -->
<!-- # style_table32 <- function(ft) { -->
<!-- #  ft %>% -->
<!-- #   font(fontname = "Times New Roman", part = "all") %>% -->
<!-- #   fontsize(size = 9) %>%  -->
<!-- #   colformat_num(digits = 3) %>% -->
<!-- #   border_outer(part = "all") %>% -->
<!-- #   bold(part = "header") %>% -->
<!-- #   # border_inner(part = "all") %>% -->
<!-- #   align(align = "center", part = "header") %>% -->
<!-- #   align(align = "center", part = "body") -->
<!-- # } -->

<!-- likelihood_row <- which(apply(table32, 1, function(row) any(row == "Likelihood"))) -->

<!-- # Add a row that spans all columns (like a section header) -->
<!--  flextable(table32) %>% land_tab_style(wd=0.55) %>%  -->
<!--  colformat_num(i = 15, j = 1:6, digits = 0) %>% -->
<!--  colformat_num(j = 2:6, digits = 3) %>% -->
<!--  compose(i = likelihood_row, j = 1, value = as_paragraph("Difference from Base Model Likelihood")) %>% -->
<!--  merge_at(i = likelihood_row, j = 1:ncol(table32), part = "body") %>% -->
<!--  align(i = likelihood_row, j = 1:ncol(table32), align = "center", part = "body") %>% -->
<!--  bold(i = likelihood_row, part = "body") %>% hline(i = c(likelihood_row-1, likelihood_row))  -->

<!--  # compose(i = likelihood_row, j = 1, value = as_paragraph("Difference from Base Model Likelihood")) %>% -->
<!--  # merge_at(i = likelihood_row, j = 1:ncol(table32), part = "body") %>% -->
<!--  # align(i = likelihood_row, j = 1:ncol(table32), align = "center", part = "body") %>% -->
<!--  # bold(i = likelihood_row, part = "body") %>% -->
<!--  # border(i = 1, j = 1:ncol(table32), part = "footer", border = fp_border(color = "transparent", width = 0)) %>% -->
<!--  # # Keep the outer bottom border of the merged footer row -->
<!--  # border(i = 1, j = 1:ncol(table32), part = "footer", border = fp_border(color = "black", width = 1))%>% -->
<!--  # style_table32()%>% fontsize(size = 11, i = likelihood_row) %>% -->
<!--  # autofit() %>% width(width = 0.6) -->


<!-- ``` -->

<!-- ```{r} -->
<!-- #| label: tbl-like-Mfemale -->
<!-- #| echo: false -->
<!-- #| warning: false -->
<!-- #| tbl-cap: "Quantities of interest when profiling over natural mortality values for females" -->

<!-- #Old table 33 -->

<!-- table33 <- read.csv(file.path(here::here(),"report/tables/NatM_uniform_Fem_GP_1_quant_table.csv"), stringsAsFactors = FALSE) -->
<!-- #Remove periods -->
<!-- colnames(table33) <- c("Natural Mortality (females)","0.121",	"0.11",	"0.099",	"0.088",	"0.132","0.143","0.154",	"0.165",	"0.176",	"0.187",	"0.198") -->

<!-- # Function for consistent table styling -->
<!-- # style_table33 <- function(ft) { -->
<!-- #  ft %>% -->
<!-- #   font(fontname = "Times New Roman", part = "all") %>% -->
<!-- #   fontsize(size = 9) %>%  -->
<!-- #   colformat_num(digits = 3) %>% -->
<!-- #   border_outer(part = "all") %>% -->
<!-- #   bold(part = "header") %>% -->
<!-- #   # border_inner(part = "all") %>% -->
<!-- #   align(align = "center", part = "header") %>% -->
<!-- #   align(align = "center", part = "body") -->
<!-- # } -->

<!-- likelihood_row <- which(apply(table33, 1, function(row) any(row == "Likelihood"))) -->

<!-- # Add a row that spans all columns (like a section header) -->
<!--  flextable(table33) %>% land_tab_style(wd=0.6) %>%  -->
<!--  colformat_num(i = 15, j = 1:6, digits = 0) %>% -->
<!--  colformat_num(j = 2:6, digits = 3) %>% -->
<!--  compose(i = likelihood_row, j = 1, value = as_paragraph("Difference from Base Model Likelihood")) %>% -->
<!--  merge_at(i = likelihood_row, j = 1:ncol(table33), part = "body") %>% -->
<!--  align(i = likelihood_row, j = 1:ncol(table33), align = "center", part = "body") %>% -->
<!--  bold(i = likelihood_row, part = "body") %>% hline(i = c(likelihood_row-1, likelihood_row)) -->

<!--  # compose(i = likelihood_row, j = 1, value = as_paragraph("Difference from Base Model Likelihood")) %>% -->
<!--  # merge_at(i = likelihood_row, j = 1:ncol(table33), part = "body") %>% -->
<!--  # align(i = likelihood_row, j = 1:ncol(table33), align = "center", part = "body") %>% -->
<!--  # bold(i = likelihood_row, part = "body") %>% -->
<!--  # border(i = 1, j = 1:ncol(table33), part = "footer", border = fp_border(color = "transparent", width = 0)) %>% -->
<!--  # # Keep the outer bottom border of the merged footer row -->
<!--  # border(i = 1, j = 1:ncol(table33), part = "footer", border = fp_border(color = "black", width = 1))%>% -->
<!--  # style_table33()%>% fontsize(size = 11, i = likelihood_row) %>% -->
<!--  # autofit() %>% width(width = 0.6) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- #| label: tbl-like-Mmale -->
<!-- #| echo: false -->
<!-- #| warning: false -->
<!-- #| tbl-cap: "Quantities of interest when profiling over natural mortality values for males" -->

<!-- #Old table 33 -->

<!-- table34 <- read.csv(file.path(here::here(),"report/tables/NatM_uniform_Mal_GP_1_quant_table.csv"), stringsAsFactors = FALSE) -->
<!-- #Remove periods -->
<!-- colnames(table34) <- c("Natural Mortality (males)","0.132",	"0.121",	"0.11",	"0.099",	"0.088",	"0.143",	"0.154",	"0.165",	"0.176",	"0.187",	"0.198") -->

<!-- # # Function for consistent table styling -->
<!-- # style_table34 <- function(ft) { -->
<!-- #  ft %>% -->
<!-- #   font(fontname = "Times New Roman", part = "all") %>% -->
<!-- #   fontsize(size = 9) %>%  -->
<!-- #   colformat_num(digits = 3) %>% -->
<!-- #   border_outer(part = "all") %>% -->
<!-- #   bold(part="header") %>% -->
<!-- #   # border_inner(part = "all") %>% -->
<!-- #   align(align = "center", part = "header") %>% -->
<!-- #   align(align = "center", part = "body") -->
<!-- # } -->

<!-- likelihood_row <- which(apply(table34, 1, function(row) any(row == "Likelihood"))) -->

<!-- # Add a row that spans all columns (like a section header) -->
<!--  flextable(table34) %>%land_tab_style(wd = 0.6) %>%  -->
<!--  colformat_num(i = 15, j = 1:6, digits = 0) %>% -->
<!--  colformat_num(j = 2:6, digits = 3) %>% -->
<!--  compose(i = likelihood_row, j = 1, value = as_paragraph("Difference from Base Model Likelihood")) %>% -->
<!--  merge_at(i = likelihood_row, j = 1:ncol(table34), part = "body") %>% -->
<!--  align(i = likelihood_row, j = 1:ncol(table34), align = "center", part = "body") %>% -->
<!--  bold(i = likelihood_row, part = "body") %>% hline(i = c(likelihood_row-1, likelihood_row)) -->

<!--  # compose(i = likelihood_row, j = 1, value = as_paragraph("Difference from Base Model Likelihood")) %>% -->
<!--  # merge_at(i = likelihood_row, j = 1:ncol(table34), part = "body") %>% -->
<!--  # align(i = likelihood_row, j = 1:ncol(table34), align = "center", part = "body") %>% -->
<!--  # bold(i = likelihood_row, part = "body") %>% bold(part = "header") %>% -->
<!--  # border(i = 1, j = 1:ncol(table34), part = "footer", border = fp_border(color = "transparent", width = 0)) %>% -->
<!--  # # Keep the outer bottom border of the merged footer row -->
<!--  # border(i = 1, j = 1:ncol(table34), part = "footer", border = fp_border(color = "black", width = 1))%>% -->
<!--  # style_table34()%>% fontsize(size = 11, i = likelihood_row) %>%   -->
<!--  # autofit() %>% width(width = 0.6) -->

<!-- ``` -->

<!-- {{< pagebreak >}} -->

```{r}
#| label: tbl-weightingcomps
#| echo: false
#| warning: false
#| tbl-cap: "Estimated data weights derived using the McAllister-Ianelli and Francis methods."

#Old table 34

table34 <- read.csv(file.path(here::here(),"figures/sensitivities/weighting_comps.csv"), stringsAsFactors = FALSE)
#Remove periods
colnames(table34) <- gsub("\\.", " ", colnames(table34))
table34 <- table34 %>% select(-c("Log Mean effN   2025 base model", "Log Mean effN   Francis"))

# Function for consistent table styling
# style_table34 <- function(ft) {
#  ft %>%
#   font(fontname = "Times New Roman", part = "all") %>%
#   border_outer(part = "all") %>%
#   bold(part = "header") %>%
#   # border_inner(part = "all") %>%
#   align(align = "center", part = "header") %>%
#   align(align = "center", part = "body") 
# }

# Add a row that spans all columns (like a section header)
 flextable(table34) %>%
 set_header_labels(names = colnames(table34), 
                   values = c("Fleet", 
                              "Composition data type", 
                              # "Log(Mean effN), McAllister Ianelli weighting", 
                              # "Log(Mean effN), Francis weighting", 
                              "McAllister Ianelli weighting (base model)", 
                              "Francis weighting (alternative)")) %>% 
 port_tab_style(wd=1.5)
 # style_table34() %>% 
 # autofit() %>% width(width = 1)


```
\elandscape

## Management

```{r}
#| label: tbl-proj-ofl
#| echo: false
#| warning: false
#| tbl-cap: "Projection of potential OFL, landings, and catch, summary biomass (age-4 and older), spawning biomass, and depletion for the base case model projected with total catch equal to the predicted ABC. The predicted OFL is the calculated total catch determined by F SPR=50%"
#| out.width: "90%"

# Function for consistent table styling
table35 <- as.data.frame(read.csv(file.path(here::here(),"report/tables/exec_summ_tables/g_Projections_ES.csv"), stringsAsFactors = FALSE))
colnames(table35) <- gsub("\\.", " ", colnames(table35))

# my_border <- fp_border(color = "black", width = 2) 

# Function for consistent table styling 
flextable(table35) %>% port_tab_style(wd=1) %>%
 # border(part = "all") %>% align(align = "left", j=2) %>% 
 # font(fontname = "Times New Roman", part = "all") %>% 
 # align(align = "center", part = "all") %>%
 # bold(part = "header")%>% border(border.top = my_border, i = 1) %>% 
 # autofit() %>% 
 colformat_num(j = 1, big.mark = "", digits = 0) # %>% 
 # fontsize(size = 9, part = "all")%>% 
 # set_table_properties(layout = "autofit") %>% width(width = 0.8)

```

{{< pagebreak >}}

```{r}
#| label: tbl-dec-table
#| echo: false
#| warning: false
#| tbl-cap: "Summary table of 12-year projections beginning in 2027 for alternate states of nature based on the axis of uncertainty (a combination of M, h, and 2013 recruitment strength). Columns range over low, mid, and high state of nature, and rows range over different assumptions of total catch levels (discards + retained). Catches in 20XX and 20XX are allocated using the percentage of landings for each fleet in 20XX."
#| out.width: "90%"

table36 <- as.data.frame(read.csv(file.path(here::here(),"data_derived/decision_table/dec_table_formatted.csv"), stringsAsFactors = FALSE))
table36$scenario <- plyr::revalue(table36$scenario,
                 c("Constant catch" = "Constant catch (9,000 K)",
                  "P*0.25" = "ACLp*=0.25, sigma=0.50",
                  "P*0.45" = "ACLp*=0.45, sigma=0.50"))

flextable(table36 %>% select(-X)) |>
 set_header_labels(values = c(scenario = "Management decision",
               yr = "Year", 
               # OFL = "OFL", 
               catch = "catch (mt)",
               SpawnBio_low = "Spawning biomass (mt)",
               dep_low = "Depletion (%)",
               SpawnBio_base = "Spawning biomass (mt)",
               dep_base = "Depletion (%)", 
               SpawnBio_high = "Spawning biomass (mt)",
               dep_high = "Depletion (%)")
          ) |>
 add_header_row(values = c("", "Low", "Base", "High"), colwidths = c(3, 2, 2, 2)) |>
 add_header_row(values = c("", "State of nature"), colwidths = c(3, 6)) |> 
 align(align = "center", part = "all") |>
 font(fontname = "Times New Roman", part = "all") |>
 fontsize(size = 9, part = "all") |>
 bold(part = "header", i = 1:2) |> 
 bold(part = "header", i = 3, j = 1) |>
 colformat_num(j = 2, big.mark = "", digits = 0) |>
 border_inner(part="header") |> border_outer() |> # header and outside border
 vline(j = c(1, 3, 5, 7)) |> hline(i = 10) |> hline(i = 20) |>
 merge_at(i = c(1:10), j = 1) |> merge_at(i = c(11:20), j = 1) |> merge_at(i = c(21:30), j = 1) |>
 # set_table_properties(layout = "autofit", align = "center") |> 
 width(width = 0.6, j = 2:(dim(table36)[2]-1)) |> 
 width(width = 0.9, j = 1)


```
