---
title: "Proposed changes to August, 2025 base model"
author: 
  - name: Ian G. Taylor
  - name: Vladlena Gertseva
  - name: Kiva L. Oken
  - name: Michael Kineen
  - name: Maurice C. Goodman
date: today
lang: en 
pdf-engine: lualatex
format: 
  pdf:
    documentclass: scrartcl
    # template-partials:
    #   - 'support_files/before-body.tex'
    include-in-header:
      - 'support_files/in-header.tex'
      # - 'support_files/pfmc.tex'
    # include-after-body:
    #   text: |
    #     \newpage{}
    #     \printnoidxglossaries
    fig-pos: 'H'
    reference-location: section
bibliography:
  - asar_references.bib
csl: 'canadian-journal-of-fisheries-and-aquatic-sciences.csl'
execute: 
  echo: false

---

```{r}
#| label: setup
#| message: false
#| warning: false

library(here)
library(dplyr)
library(r4ss)

base_location <- here('models/2025 base model')
base_in <- SS_read(base_location)
base_out <- SS_output(base_location, verbose = FALSE, printstats = FALSE, covar = FALSE)

# insert any other preamble code here
```

```{r, results='asis'}
#| label: 'disclaimer'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child(here('report/00a_disclaimer.qmd'), quiet = TRUE)
cat(a, sep = '\n')

```

# New proposed base model

```{r, results='asis'}
#| label: 'new_base'
#| warning: false
a <- knitr::knit_child('new_base_description.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

# Bridging from the August 2025 model to the new proposed base model

```{r, results='asis'}
#| label: 'bridging'
#| warning: false
a <- knitr::knit_child('bridging.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

# Diagnostics from new proposed base model

```{r, results='asis'}
#| label: 'diagnostics'
#| warning: false
a <- knitr::knit_child('diagnostics.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

# Projections for new proposed base model

```{r, results='asis'}
#| label: 'management'
#| warning: false
a <- knitr::knit_child('management.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

# References

```{r, results='asis'}
#| label: 'references'
#| warning: false
a <- knitr::knit_child(here('report/07_references.qmd'), quiet = TRUE)
```
