---
title: "Explore discard data"
author: "Alaia"
date: "2025-02-05"
output: html_document
---
WGCOP data need to be downloaded in data_provided folder from google drive
# Install and load package
```{r}
library(ggplot2)
library(reshape2)
library(here)
library(dplyr)


```

# Visualizing the Data 
## Load and plot WGCOP data 

```{r}
data_discard_non_catch <- read.csv(here("data_provided/wcgop", "discard_rates_noncatch_share.csv")) %>%
  select(year, fleet, obs_discard) %>%
  rename(observed_discard_mt = obs_discard) %>%
  mutate(fleet = recode(fleet, 
         "bottomtrawl-coastwide" = "Bottom trawl",
         "hook-and-line-coastwide" = "Hook & Line"))

data_discard_catch<- read.csv(here("data_provided/wcgop", "discard_rates_combined_catch_share.csv")) %>%
  select("year", "fleet", "observed_discard_mt")%>%
  mutate(fleet = recode(fleet, 
         "bottomtrawl-coastwide" = "Bottom trawl",
         "hook-and-line-coastwide" = "Hook & Line",
         "midwaterrockfish-coastwide" = "Midwater trawl",
         "midwaterhake-coastwide" = "Midwater trawl"))

data_discard <- rbind(data_discard_non_catch, data_discard_catch)

ggplot(data_discard, aes(x = year, y = observed_discard_mt, fill = fleet)) +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9"))+
  geom_col() +  
  theme_minimal() +
    labs(x = "Year", y = "Discards (mt)", 
       title = paste0("Discards (WGCOP)"))+
  theme(strip.text = element_text(face = "bold"))




```




## Discards length composition 
```{r}

data <- read.csv(here("data_provided/wcgop", "biological_discard_lengths.csv"))
data <- data[,-c(2,4,5,6,32:56)]
names(data) <- c("year", "fleet" , seq(8,56,2))
data <- melt(data, c("fleet", "year"))
data$variable = as.numeric(as.character(data$variable))

fleet_type <- unique(data$fleet)

ggplot(data[data$fleet==fleet_type[1],], aes(x = variable, y = value)) +
  geom_col() +
  facet_wrap(~ year, scales = "free_y") +
  labs(x = "Length bin (cm)", y = "%", 
       title = paste0("Discards by length bin by year for ",fleet_type[1])) +
  theme_minimal() +
  theme(legend.position = "none", 
        strip.text = element_text(face = "bold")) 

ggplot(data[data$fleet==fleet_type[2],], aes(x = variable, y = value)) +
  geom_col() +
  facet_wrap(~ year, scales = "free_y") +
  labs(x = "Length bin (cm)", y = "%", 
       title = paste0("Discards by length bin by year for ",fleet_type[2]))+
  theme_minimal() +
  theme(legend.position = "none", 
        strip.text = element_text(face = "bold")) 

ggplot(data[data$fleet==fleet_type[3],], aes(x = variable, y = value)) +
  geom_col() +
  facet_wrap(~ year, scales = "free_y") +
  labs(x = "Length bin (cm)", y = "%", 
       title = paste0("Discards by length bin by year for ",fleet_type[3])) +
  theme_minimal() +
  theme(legend.position = "none", 
        strip.text = element_text(face = "bold")) 

ggplot(data[data$fleet==fleet_type[4],], aes(x = variable, y = value)) +
  geom_col() +
  facet_wrap(~ year, scales = "free_y") +
  labs(x = "Length bin (cm)", y = "%", 
       title = paste0("Discards by length bin by year for ",fleet_type[4]))+
  theme_minimal() +
  theme(legend.position = "none", 
        strip.text = element_text(face = "bold")) 


# )
```

```{r}

# Bottom trawl
{plot(data[data$fleet==fleet_type[1],]$year, data[data$fleet==fleet_type[1],]$variable, xlab = "Year", ylab = "Length (cm)", main = "WGCOP discards by length by year (Bottom Trawl)",
     xlim = range(data[data$fleet==fleet_type[1],]$year), ylim = c(8, 62), type = "n")  
symbols(data[data$fleet==fleet_type[1],]$year, data[data$fleet==fleet_type[1],]$variable, circles = sqrt(data[data$fleet==fleet_type[1],]$value/pi), inches = 0.1, add = TRUE, bg = "white")

legend_x <- 2007
legend_y <- 60 
legend_sizes <- c(0.01, 0.4, 0.8) #Identical to 2019 updates
legend_circles <- sqrt(legend_sizes/pi)
symbols(legend_x-0.5 + (1:length(legend_sizes)) * 3,rep(legend_y+0.5, length(legend_sizes)) ,
        circles = legend_circles, inches = 0.1, add = TRUE, bg = "white")
text(legend_x + (1:length(legend_sizes)) * 3,rep(legend_y + 1, length(legend_sizes)) ,
     labels = legend_sizes, adj = 0)}



# Bottom trawl
{plot(data[data$fleet==fleet_type[2],]$year, data[data$fleet==fleet_type[2],]$variable, xlab = "Year", ylab = "Length (cm)", main = "WGCOP discards by length by year",
     xlim = range(data[data$fleet==fleet_type[2],]$year), ylim = c(8, 62), type = "n")  
symbols(data[data$fleet==fleet_type[2],]$year, data[data$fleet==fleet_type[2],]$variable, circles = sqrt(data[data$fleet==fleet_type[2],]$value/pi), inches = 0.1, add = TRUE, bg = "white")

legend_x <- 2007
legend_y <- 60 
legend_sizes <- c(0.01, 0.4, 0.8) #Identical to 2019 updates
legend_circles <- sqrt(legend_sizes/pi)
symbols(legend_x-0.5 + (1:length(legend_sizes)) * 3,rep(legend_y+0.5, length(legend_sizes)) ,
        circles = legend_circles, inches = 0.1, add = TRUE, bg = "white")
text(legend_x + (1:length(legend_sizes)) * 3,rep(legend_y + 1, length(legend_sizes)) ,
     labels = legend_sizes, adj = 0)}

```


```{r}
data_agg <- data %>%
  group_by(year, variable)%>%
  mutate(value = sum(value))%>%
  distinct(year, variable, value)%>%
  group_by(year)%>%
  mutate(value = value  /sum(value)*100)



ggplot(data_agg, aes(x = variable, y = value)) +
  geom_col() +
  facet_wrap(~ year, scales = "free_y") +
  labs(x = "Length bin (cm)", y = "%", 
       title = paste0("WGCOP discards by length bin by year"))+
  theme_minimal() +
  theme(legend.position = "none", 
        strip.text = element_text(face = "bold")) 



```


```{r}
# Size comp by year
dev.new(width=5, height=20, unit="in")
{plot(data_agg$year, data_agg$variable, xlab = "Year", ylab = "Length (cm)", main = "WGCOP discards by length by year",
     xlim = range(data_agg$year), ylim = c(8, 62), type = "n")  
symbols(data_agg$year, data_agg$variable, circles = sqrt(data_agg$value/pi), inches = 0.1, add = TRUE, bg = "white")


# Legend

legend_x <- 2007
legend_y <- 60 
legend_sizes <- c(0.01, 0.4, 0.8) #Identical to 2019 updates
legend_circles <- sqrt(legend_sizes/pi)
symbols(legend_x-0.5 + (1:length(legend_sizes)) * 3,rep(legend_y+0.5, length(legend_sizes)) ,
        circles = legend_circles, inches = 0.1, add = TRUE, bg = "white")
text(legend_x + (1:length(legend_sizes)) * 3,rep(legend_y + 1, length(legend_sizes)) ,
     labels = legend_sizes, adj = 0)}









```




